# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_Tafonomia_ui.ui'
#
# Created: Mon Oct 10 17:08:12 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog_tafonomia(object):
    def setupUi(self, Dialog_tafonomia):
        Dialog_tafonomia.setObjectName("Dialog_tafonomia")
        Dialog_tafonomia.resize(671, 839)
        Dialog_tafonomia.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/iconGrave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_tafonomia.setWindowIcon(icon)
        self.gridLayout_7 = QtGui.QGridLayout(Dialog_tafonomia)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_first_rec = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_first_rec.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/5_leftArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName("pushButton_first_rec")
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 0, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_prev_rec.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/4_leftArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon2)
        self.pushButton_prev_rec.setObjectName("pushButton_prev_rec")
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 1, 1, 2)
        self.pushButton_next_rec = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_next_rec.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/6_rightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon3)
        self.pushButton_next_rec.setObjectName("pushButton_next_rec")
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_last_rec.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/7_rightArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon4)
        self.pushButton_last_rec.setObjectName("pushButton_last_rec")
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/newrec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon5)
        self.pushButton_new_rec.setObjectName("pushButton_new_rec")
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/b_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon6)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon7)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(70, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/new_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName("pushButton_new_search")
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon9)
        self.pushButton_search_go.setObjectName("pushButton_search_go")
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon10)
        self.pushButton_sort.setObjectName("pushButton_sort")
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/view_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon11)
        self.pushButton_view_all.setObjectName("pushButton_view_all")
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(Dialog_tafonomia)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_42 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_43 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(Dialog_tafonomia)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName("label_status")
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText("")
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName("label_sort")
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName("label_rec_corrente")
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName("label_rec_tot")
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_8 = QtGui.QFrame(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 7)
        self.comboBox_sito = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(250, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName("comboBox_sito")
        self.comboBox_sito.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_sito, 1, 0, 1, 2)
        self.lineEdit_nr_scheda = QtGui.QLineEdit(Dialog_tafonomia)
        self.lineEdit_nr_scheda.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_nr_scheda.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_nr_scheda.setObjectName("lineEdit_nr_scheda")
        self.gridLayout_7.addWidget(self.lineEdit_nr_scheda, 1, 2, 1, 2)
        self.comboBox_sigla_struttura = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_sigla_struttura.setEnabled(False)
        self.comboBox_sigla_struttura.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_sigla_struttura.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboBox_sigla_struttura.setEditable(True)
        self.comboBox_sigla_struttura.setObjectName("comboBox_sigla_struttura")
        self.gridLayout_7.addWidget(self.comboBox_sigla_struttura, 1, 4, 1, 1)
        self.comboBox_nr_struttura = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_nr_struttura.setEnabled(False)
        self.comboBox_nr_struttura.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_nr_struttura.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_nr_struttura.setFont(font)
        self.comboBox_nr_struttura.setEditable(True)
        self.comboBox_nr_struttura.setObjectName("comboBox_nr_struttura")
        self.gridLayout_7.addWidget(self.comboBox_nr_struttura, 1, 5, 1, 1)
        self.comboBox_nr_individuo = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_nr_individuo.setEnabled(False)
        self.comboBox_nr_individuo.setEditable(True)
        self.comboBox_nr_individuo.setObjectName("comboBox_nr_individuo")
        self.gridLayout_7.addWidget(self.comboBox_nr_individuo, 1, 6, 1, 1)
        self.label = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(221, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 2, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 2, 3, 1, 1)
        self.label_32 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 2, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(81, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 2, 5, 1, 1)
        self.label_19 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 2, 6, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.comboBox_rito = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_rito.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_rito.setFont(font)
        self.comboBox_rito.setEditable(True)
        self.comboBox_rito.setObjectName("comboBox_rito")
        self.comboBox_rito.addItem("")
        self.comboBox_rito.addItem("")
        self.comboBox_rito.addItem("")
        self.comboBox_rito.addItem("")
        self.comboBox_rito.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_rito)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 3, 0, 1, 4)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtGui.QTabWidget(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_14 = QtGui.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_14.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.textEdit_descrizione_taf = QtGui.QTextEdit(self.tab)
        self.textEdit_descrizione_taf.setMinimumSize(QtCore.QSize(250, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_taf.setFont(font)
        self.textEdit_descrizione_taf.setObjectName("textEdit_descrizione_taf")
        self.gridLayout_10.addWidget(self.textEdit_descrizione_taf, 0, 0, 1, 1)
        self.textEdit_interpretazione_taf = QtGui.QTextEdit(self.tab)
        self.textEdit_interpretazione_taf.setMinimumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione_taf.setFont(font)
        self.textEdit_interpretazione_taf.setObjectName("textEdit_interpretazione_taf")
        self.gridLayout_10.addWidget(self.textEdit_interpretazione_taf, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 1, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_10, 1, 0, 1, 5)
        self.label_3 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_14.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_segnacoli = QtGui.QComboBox(self.tab)
        self.comboBox_segnacoli.setEditable(True)
        self.comboBox_segnacoli.setObjectName("comboBox_segnacoli")
        self.comboBox_segnacoli.addItem("")
        self.comboBox_segnacoli.setItemText(0, "")
        self.comboBox_segnacoli.addItem("")
        self.comboBox_segnacoli.addItem("")
        self.comboBox_segnacoli.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_segnacoli, 2, 1, 1, 1)
        self.comboBox_canale_libatorio = QtGui.QComboBox(self.tab)
        self.comboBox_canale_libatorio.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_canale_libatorio.setEditable(True)
        self.comboBox_canale_libatorio.setObjectName("comboBox_canale_libatorio")
        self.comboBox_canale_libatorio.addItem("")
        self.comboBox_canale_libatorio.setItemText(0, "")
        self.comboBox_canale_libatorio.addItem("")
        self.comboBox_canale_libatorio.addItem("")
        self.comboBox_canale_libatorio.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_canale_libatorio, 2, 2, 1, 2)
        self.comboBox_oggetti_esterno = QtGui.QComboBox(self.tab)
        self.comboBox_oggetti_esterno.setEditable(True)
        self.comboBox_oggetti_esterno.setObjectName("comboBox_oggetti_esterno")
        self.comboBox_oggetti_esterno.addItem("")
        self.comboBox_oggetti_esterno.setItemText(0, "")
        self.comboBox_oggetti_esterno.addItem("")
        self.comboBox_oggetti_esterno.addItem("")
        self.comboBox_oggetti_esterno.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_oggetti_esterno, 2, 4, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_14.addWidget(self.label_30, 3, 0, 1, 1)
        self.comboBox_conservazione_taf = QtGui.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_conservazione_taf.setFont(font)
        self.comboBox_conservazione_taf.setEditable(True)
        self.comboBox_conservazione_taf.setObjectName("comboBox_conservazione_taf")
        self.comboBox_conservazione_taf.addItem("")
        self.comboBox_conservazione_taf.addItem("")
        self.comboBox_conservazione_taf.addItem("")
        self.comboBox_conservazione_taf.addItem("")
        self.comboBox_conservazione_taf.addItem("")
        self.comboBox_conservazione_taf.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_conservazione_taf, 3, 1, 2, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_14.addWidget(self.label_8, 3, 2, 1, 2)
        self.label_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_14.addWidget(self.label_4, 3, 4, 1, 1)
        self.comboBox_copertura_tipo = QtGui.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_copertura_tipo.setFont(font)
        self.comboBox_copertura_tipo.setEditable(True)
        self.comboBox_copertura_tipo.setObjectName("comboBox_copertura_tipo")
        self.comboBox_copertura_tipo.addItem("")
        self.comboBox_copertura_tipo.addItem("")
        self.comboBox_copertura_tipo.addItem("")
        self.comboBox_copertura_tipo.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_copertura_tipo, 5, 0, 2, 1)
        self.comboBox_tipo_contenitore_resti = QtGui.QComboBox(self.tab)
        self.comboBox_tipo_contenitore_resti.setEditable(True)
        self.comboBox_tipo_contenitore_resti.setObjectName("comboBox_tipo_contenitore_resti")
        self.comboBox_tipo_contenitore_resti.addItem("")
        self.comboBox_tipo_contenitore_resti.addItem("")
        self.comboBox_tipo_contenitore_resti.addItem("")
        self.comboBox_tipo_contenitore_resti.addItem("")
        self.comboBox_tipo_contenitore_resti.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_tipo_contenitore_resti, 5, 1, 2, 1)
        self.label_85 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.gridLayout_14.addWidget(self.label_85, 7, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_14.addWidget(self.label_35, 7, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 8, 0, 1, 1)
        self.lineEdit_orientamento_asse = QtGui.QLineEdit(self.tab)
        self.lineEdit_orientamento_asse.setObjectName("lineEdit_orientamento_asse")
        self.gridLayout_14.addWidget(self.lineEdit_orientamento_asse, 9, 0, 1, 1)
        self.lineEdit_orientamento_azimut = QtGui.QLineEdit(self.tab)
        self.lineEdit_orientamento_azimut.setObjectName("lineEdit_orientamento_azimut")
        self.gridLayout_14.addWidget(self.lineEdit_orientamento_azimut, 9, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_14.addWidget(self.label_31, 10, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_14.addWidget(self.label_47, 10, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_17 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 0, 0, 1, 2)
        self.comboBox_corredo_presenza = QtGui.QComboBox(self.tab_5)
        self.comboBox_corredo_presenza.setEditable(True)
        self.comboBox_corredo_presenza.setObjectName("comboBox_corredo_presenza")
        self.comboBox_corredo_presenza.addItem("")
        self.comboBox_corredo_presenza.addItem("")
        self.comboBox_corredo_presenza.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_corredo_presenza, 1, 0, 1, 3)
        self.tableWidget_corredo_tipo = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_corredo_tipo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_corredo_tipo.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_corredo_tipo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_corredo_tipo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_corredo_tipo.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_corredo_tipo.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_corredo_tipo.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_corredo_tipo.setRowCount(1)
        self.tableWidget_corredo_tipo.setColumnCount(3)
        self.tableWidget_corredo_tipo.setObjectName("tableWidget_corredo_tipo")
        self.tableWidget_corredo_tipo.setColumnCount(3)
        self.tableWidget_corredo_tipo.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_corredo_tipo.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_corredo_tipo.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_corredo_tipo.setHorizontalHeaderItem(2, item)
        self.gridLayout_11.addWidget(self.tableWidget_corredo_tipo, 2, 0, 1, 3)
        self.pushButton_insert_row_corredo = QtGui.QPushButton(self.tab_5)
        self.pushButton_insert_row_corredo.setObjectName("pushButton_insert_row_corredo")
        self.gridLayout_11.addWidget(self.pushButton_insert_row_corredo, 3, 0, 1, 1)
        self.pushButton_remove_row_corredo = QtGui.QPushButton(self.tab_5)
        self.pushButton_remove_row_corredo.setObjectName("pushButton_remove_row_corredo")
        self.gridLayout_11.addWidget(self.pushButton_remove_row_corredo, 3, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(490, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 3, 2, 1, 1)
        self.textEdit_descrizione_corredo = QtGui.QTextEdit(self.tab_5)
        self.textEdit_descrizione_corredo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_corredo.setFont(font)
        self.textEdit_descrizione_corredo.setObjectName("textEdit_descrizione_corredo")
        self.gridLayout_11.addWidget(self.textEdit_descrizione_corredo, 4, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 5, 0, 1, 2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_lunghezza_scheletro = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_lunghezza_scheletro.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_lunghezza_scheletro.setFont(font)
        self.lineEdit_lunghezza_scheletro.setObjectName("lineEdit_lunghezza_scheletro")
        self.gridLayout_15.addWidget(self.lineEdit_lunghezza_scheletro, 0, 0, 1, 1)
        self.comboBox_posizione_scheletro = QtGui.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_posizione_scheletro.setFont(font)
        self.comboBox_posizione_scheletro.setEditable(True)
        self.comboBox_posizione_scheletro.setObjectName("comboBox_posizione_scheletro")
        self.comboBox_posizione_scheletro.addItem("")
        self.comboBox_posizione_scheletro.setItemText(0, "")
        self.comboBox_posizione_scheletro.addItem("")
        self.comboBox_posizione_scheletro.addItem("")
        self.comboBox_posizione_scheletro.addItem("")
        self.comboBox_posizione_scheletro.addItem("")
        self.comboBox_posizione_scheletro.addItem("")
        self.comboBox_posizione_scheletro.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_posizione_scheletro, 0, 1, 1, 1)
        self.comboBox_posizione_cranio = QtGui.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_posizione_cranio.setFont(font)
        self.comboBox_posizione_cranio.setEditable(True)
        self.comboBox_posizione_cranio.setObjectName("comboBox_posizione_cranio")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.setItemText(0, "")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.addItem("")
        self.comboBox_posizione_cranio.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_posizione_cranio, 0, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_15.addWidget(self.label_33, 1, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_15.addWidget(self.label_37, 1, 1, 1, 1)
        self.label_86 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.gridLayout_15.addWidget(self.label_86, 1, 2, 1, 1)
        self.comboBox_arti_superiori = QtGui.QComboBox(self.tab_2)
        self.comboBox_arti_superiori.setEditable(True)
        self.comboBox_arti_superiori.setObjectName("comboBox_arti_superiori")
        self.comboBox_arti_superiori.addItem("")
        self.comboBox_arti_superiori.setItemText(0, "")
        self.comboBox_arti_superiori.addItem("")
        self.comboBox_arti_superiori.addItem("")
        self.comboBox_arti_superiori.addItem("")
        self.comboBox_arti_superiori.addItem("")
        self.comboBox_arti_superiori.addItem("")
        self.comboBox_arti_superiori.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_arti_superiori, 2, 0, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_11 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 0, 0, 1, 1)
        self.comboBox_disturbato = QtGui.QComboBox(self.tab_2)
        self.comboBox_disturbato.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_disturbato.setObjectName("comboBox_disturbato")
        self.comboBox_disturbato.addItem("")
        self.comboBox_disturbato.addItem("")
        self.comboBox_disturbato.addItem("")
        self.comboBox_disturbato.setItemText(2, "")
        self.gridLayout_12.addWidget(self.comboBox_disturbato, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_12.addWidget(self.label_12, 1, 0, 1, 1)
        self.comboBox_completo = QtGui.QComboBox(self.tab_2)
        self.comboBox_completo.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_completo.setObjectName("comboBox_completo")
        self.comboBox_completo.addItem("")
        self.comboBox_completo.addItem("")
        self.comboBox_completo.addItem("")
        self.comboBox_completo.setItemText(2, "")
        self.gridLayout_12.addWidget(self.comboBox_completo, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 2, 0, 1, 1)
        self.comboBox_in_connessione = QtGui.QComboBox(self.tab_2)
        self.comboBox_in_connessione.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_in_connessione.setObjectName("comboBox_in_connessione")
        self.comboBox_in_connessione.addItem("")
        self.comboBox_in_connessione.addItem("")
        self.comboBox_in_connessione.addItem("")
        self.comboBox_in_connessione.setItemText(2, "")
        self.gridLayout_12.addWidget(self.comboBox_in_connessione, 2, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_12, 2, 1, 4, 2)
        self.label_5 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 3, 0, 1, 1)
        self.comboBox_arti_inferiori = QtGui.QComboBox(self.tab_2)
        self.comboBox_arti_inferiori.setEditable(True)
        self.comboBox_arti_inferiori.setObjectName("comboBox_arti_inferiori")
        self.comboBox_arti_inferiori.addItem("")
        self.comboBox_arti_inferiori.setItemText(0, "")
        self.comboBox_arti_inferiori.addItem("")
        self.comboBox_arti_inferiori.addItem("")
        self.comboBox_arti_inferiori.addItem("")
        self.comboBox_arti_inferiori.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_arti_inferiori, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 5, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem7, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_insert_row_caratteristiche = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_caratteristiche.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_caratteristiche.setFont(font)
        self.pushButton_insert_row_caratteristiche.setObjectName("pushButton_insert_row_caratteristiche")
        self.gridLayout_13.addWidget(self.pushButton_insert_row_caratteristiche, 2, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem8, 4, 0, 1, 1)
        self.tableWidget_caratteristiche = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_caratteristiche.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_caratteristiche.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_caratteristiche.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_caratteristiche.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_caratteristiche.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_caratteristiche.setRowCount(1)
        self.tableWidget_caratteristiche.setColumnCount(2)
        self.tableWidget_caratteristiche.setObjectName("tableWidget_caratteristiche")
        self.tableWidget_caratteristiche.setColumnCount(2)
        self.tableWidget_caratteristiche.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_caratteristiche.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_caratteristiche.setHorizontalHeaderItem(1, item)
        self.gridLayout_13.addWidget(self.tableWidget_caratteristiche, 0, 0, 2, 1)
        self.pushButton_remove_row_caratteristiche = QtGui.QPushButton(self.tab_3)
        self.pushButton_remove_row_caratteristiche.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_remove_row_caratteristiche.setObjectName("pushButton_remove_row_caratteristiche")
        self.gridLayout_13.addWidget(self.pushButton_remove_row_caratteristiche, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_36 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_46 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_5.addWidget(self.label_46)
        self.pushButton_showLayer = QtGui.QPushButton(self.tab_4)
        self.pushButton_showLayer.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showLayer.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/sheet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_showLayer.setIcon(icon12)
        self.pushButton_showLayer.setObjectName("pushButton_showLayer")
        self.horizontalLayout_5.addWidget(self.pushButton_showLayer)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_38 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_6.addWidget(self.label_38)
        self.toolButtonGis = QtGui.QToolButton(self.tab_4)
        self.toolButtonGis.setEnabled(False)
        self.toolButtonGis.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonGis.setToolTip("")
        self.toolButtonGis.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/GIS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGis.setIcon(icon13)
        self.toolButtonGis.setCheckable(True)
        self.toolButtonGis.setChecked(False)
        self.toolButtonGis.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonGis.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonGis.setObjectName("toolButtonGis")
        self.horizontalLayout_6.addWidget(self.toolButtonGis)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.gridLayout_8.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_39 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_7.addWidget(self.label_39)
        self.toolButtonPreview = QtGui.QToolButton(self.tab_4)
        self.toolButtonPreview.setEnabled(False)
        self.toolButtonPreview.setToolTip("")
        self.toolButtonPreview.setIcon(icon13)
        self.toolButtonPreview.setCheckable(True)
        self.toolButtonPreview.setChecked(False)
        self.toolButtonPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPreview.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPreview.setObjectName("toolButtonPreview")
        self.horizontalLayout_7.addWidget(self.toolButtonPreview)
        self.toolButtonPan = QtGui.QToolButton(self.tab_4)
        self.toolButtonPan.setEnabled(False)
        self.toolButtonPan.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonPan.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/mActionPan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPan.setIcon(icon14)
        self.toolButtonPan.setCheckable(True)
        self.toolButtonPan.setChecked(False)
        self.toolButtonPan.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPan.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPan.setObjectName("toolButtonPan")
        self.horizontalLayout_7.addWidget(self.toolButtonPan)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 3, 0, 1, 2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_40 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_8.addWidget(self.label_40)
        self.pushButton_showSelectedFeatures = QtGui.QPushButton(self.tab_4)
        self.pushButton_showSelectedFeatures.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showSelectedFeatures.setFont(font)
        self.pushButton_showSelectedFeatures.setIcon(icon12)
        self.pushButton_showSelectedFeatures.setObjectName("pushButton_showSelectedFeatures")
        self.horizontalLayout_8.addWidget(self.pushButton_showSelectedFeatures)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 4, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_41 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_9.addWidget(self.label_41)
        self.pushButton_pdf_exp = QtGui.QPushButton(self.tab_4)
        self.pushButton_pdf_exp.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pdf_exp.setFont(font)
        self.pushButton_pdf_exp.setIcon(icon12)
        self.pushButton_pdf_exp.setObjectName("pushButton_pdf_exp")
        self.horizontalLayout_9.addWidget(self.pushButton_pdf_exp)
        self.pushButton_exp_index_us = QtGui.QPushButton(self.tab_4)
        self.pushButton_exp_index_us.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exp_index_us.setFont(font)
        self.pushButton_exp_index_us.setIcon(icon12)
        self.pushButton_exp_index_us.setObjectName("pushButton_exp_index_us")
        self.horizontalLayout_9.addWidget(self.pushButton_exp_index_us)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 5, 0, 1, 2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_44 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_10.addWidget(self.label_44)
        self.toolButtonPreviewMedia = QtGui.QToolButton(self.tab_4)
        self.toolButtonPreviewMedia.setEnabled(False)
        self.toolButtonPreviewMedia.setMinimumSize(QtCore.QSize(109, 0))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/photo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPreviewMedia.setIcon(icon15)
        self.toolButtonPreviewMedia.setCheckable(True)
        self.toolButtonPreviewMedia.setObjectName("toolButtonPreviewMedia")
        self.horizontalLayout_10.addWidget(self.toolButtonPreviewMedia)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 6, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_45 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_11.addWidget(self.label_45)
        self.pushButton_export_matrix = QtGui.QPushButton(self.tab_4)
        self.pushButton_export_matrix.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_export_matrix.setFont(font)
        self.pushButton_export_matrix.setIcon(icon12)
        self.pushButton_export_matrix.setObjectName("pushButton_export_matrix")
        self.horizontalLayout_11.addWidget(self.pushButton_export_matrix)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.gridLayout_8.addLayout(self.horizontalLayout_11, 7, 1, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_70 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_9.addWidget(self.label_70, 0, 0, 1, 1)
        self.comboBox_sito_rappcheck = QtGui.QComboBox(self.tab_4)
        self.comboBox_sito_rappcheck.setEnabled(False)
        self.comboBox_sito_rappcheck.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito_rappcheck.setFont(font)
        self.comboBox_sito_rappcheck.setMouseTracking(True)
        self.comboBox_sito_rappcheck.setEditable(False)
        self.comboBox_sito_rappcheck.setMaxVisibleItems(99999)
        self.comboBox_sito_rappcheck.setMaxCount(2147483647)
        self.comboBox_sito_rappcheck.setObjectName("comboBox_sito_rappcheck")
        self.comboBox_sito_rappcheck.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_sito_rappcheck, 1, 0, 1, 1)
        self.pushButton_rapp_check = QtGui.QPushButton(self.tab_4)
        self.pushButton_rapp_check.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rapp_check.setFont(font)
        self.pushButton_rapp_check.setIcon(icon12)
        self.pushButton_rapp_check.setObjectName("pushButton_rapp_check")
        self.gridLayout_9.addWidget(self.pushButton_rapp_check, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 8, 0, 1, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 4, 0, 1, 7)

        self.retranslateUi(Dialog_tafonomia)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog_tafonomia)

    def retranslateUi(self, Dialog_tafonomia):
        Dialog_tafonomia.setWindowTitle(QtGui.QApplication.translate("Dialog_tafonomia", "pyArchInit Gestione Scavi - Scheda Tafonomica", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog_tafonomia", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Reload DB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("Dialog_tafonomia", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog_tafonomia", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("Dialog_tafonomia", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog_tafonomia", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("Dialog_tafonomia", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Sito ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Nr Scheda", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Rif. struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Nr Individuo        ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Rito", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Riduzione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Ad inumazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Ad incinerazione diretta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Ad incinerazione indiretta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Mummuficazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_taf.setHtml(QtGui.QApplication.translate("Dialog_tafonomia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Interpretazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Segnacoli", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_segnacoli.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_segnacoli.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_segnacoli.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_canale_libatorio.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_canale_libatorio.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_canale_libatorio.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_oggetti_esterno.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_oggetti_esterno.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_oggetti_esterno.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Stato di conservazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Insufficiente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Scarso", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Sufficiente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Discreto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Buono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(5, QtGui.QApplication.translate("Dialog_tafonomia", "Ottimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Canale libatorio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Oggetti rinvenuti all\'esterno", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copertura_tipo.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Non rilevabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copertura_tipo.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Copertura assente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copertura_tipo.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Tegole alla cappuccina", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copertura_tipo.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "In cassa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Entro sudario", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "In cassa fittile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "In cassa lignea", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "In urna litica", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Nella terra", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo copertura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo contenitore resti", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Orientamento", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_orientamento_azimut.setText(QtGui.QApplication.translate("Dialog_tafonomia", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Asse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Azimut", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog_tafonomia", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Corredo ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_corredo_presenza.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Corredo assente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_corredo_presenza.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Corredo presente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_corredo_presenza.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_corredo_tipo.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Nr. reperto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_corredo_tipo.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo di corredo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_corredo_tipo.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Descrizione", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_corredo.setText(QtGui.QApplication.translate("Dialog_tafonomia", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_corredo.setText(QtGui.QApplication.translate("Dialog_tafonomia", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_corredo.setHtml(QtGui.QApplication.translate("Dialog_tafonomia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog_tafonomia", "Corredo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Supino", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Prono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Posizione fetale", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(5, QtGui.QApplication.translate("Dialog_tafonomia", "Su lato dx", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(6, QtGui.QApplication.translate("Dialog_tafonomia", "Su lato sx", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Nord", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Est", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Ovest", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(5, QtGui.QApplication.translate("Dialog_tafonomia", "Sud", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(6, QtGui.QApplication.translate("Dialog_tafonomia", "Nord-Est", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(7, QtGui.QApplication.translate("Dialog_tafonomia", "Nord-Ovest", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(8, QtGui.QApplication.translate("Dialog_tafonomia", "Sud-Est", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(9, QtGui.QApplication.translate("Dialog_tafonomia", "Sud-Ovest", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Lunghezza scheletro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione scheletro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione cranio", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Braccia lungo il corpo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Braccia Incrociate sul petto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Braccia Incrociate sul bacino", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(5, QtGui.QApplication.translate("Dialog_tafonomia", "Mani congiunte sul petto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(6, QtGui.QApplication.translate("Dialog_tafonomia", "Mani congiunte sul bacino  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Disturbato", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_disturbato.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_disturbato.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Completo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_completo.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_completo.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog_tafonomia", "In connessione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_in_connessione.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_in_connessione.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione arti superiori", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_inferiori.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Distesi", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_inferiori.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Incrociati", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_inferiori.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Asimmetrici", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_inferiori.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione arti infeiori", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog_tafonomia", "Resti osteologici", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_caratteristiche.setText(QtGui.QApplication.translate("Dialog_tafonomia", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_caratteristiche.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo caratteristica", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_caratteristiche.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_caratteristiche.setText(QtGui.QApplication.translate("Dialog_tafonomia", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog_tafonomia", "Caratteristiche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Dialog_tafonomia", "GIS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Mostra layer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showLayer.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showLayer.setText(QtGui.QApplication.translate("Dialog_tafonomia", "apri layer US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Visualizzazione GIS", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGis.setShortcut(QtGui.QApplication.translate("Dialog_tafonomia", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Attivazione Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setShortcut(QtGui.QApplication.translate("Dialog_tafonomia", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Pan tool", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setShortcut(QtGui.QApplication.translate("Dialog_tafonomia", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Apri schede US selezionate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setText(QtGui.QApplication.translate("Dialog_tafonomia", "apri schede US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Esporta schede US in formato PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Singole schede", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exp_index_us.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Elenco US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreviewMedia.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Esporta Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export_matrix.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export_matrix.setText(QtGui.QApplication.translate("Dialog_tafonomia", "export Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Controlla rapporti stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito_rappcheck.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rapp_check.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rapp_check.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Check, go!!!!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog_tafonomia", "Tools", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
