# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_Struttura_ui.ui'
#
# Created: Mon Aug 29 17:00:44 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogStruttura(object):
    def setupUi(self, DialogStruttura):
        DialogStruttura.setObjectName("DialogStruttura")
        DialogStruttura.resize(667, 766)
        DialogStruttura.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/iconStrutt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogStruttura.setWindowIcon(icon)
        self.layoutWidget = QtGui.QWidget(DialogStruttura)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 283))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_first_rec = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_first_rec.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/5_leftArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName("pushButton_first_rec")
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 0, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_prev_rec.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/4_leftArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon2)
        self.pushButton_prev_rec.setObjectName("pushButton_prev_rec")
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 1, 1, 2)
        self.pushButton_next_rec = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_next_rec.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/6_rightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon3)
        self.pushButton_next_rec.setObjectName("pushButton_next_rec")
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_last_rec.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/7_rightArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon4)
        self.pushButton_last_rec.setObjectName("pushButton_last_rec")
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/newrec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon5)
        self.pushButton_new_rec.setObjectName("pushButton_new_rec")
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/b_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon6)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon7)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(70, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/new_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName("pushButton_new_search")
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon9)
        self.pushButton_search_go.setObjectName("pushButton_search_go")
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon10)
        self.pushButton_sort.setObjectName("pushButton_sort")
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/view_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon11)
        self.pushButton_view_all.setObjectName("pushButton_view_all")
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_42 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_43 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(self.layoutWidget)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName("label_status")
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText("")
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName("label_sort")
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName("label_rec_corrente")
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName("label_rec_tot")
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_8 = QtGui.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.comboBox_sito = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName("comboBox_sito")
        self.gridLayout_18.addWidget(self.comboBox_sito, 0, 0, 1, 1)
        self.numero_struttura = QtGui.QLineEdit(self.layoutWidget)
        self.numero_struttura.setEnabled(False)
        self.numero_struttura.setMinimumSize(QtCore.QSize(61, 21))
        self.numero_struttura.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.numero_struttura.setFont(font)
        self.numero_struttura.setObjectName("numero_struttura")
        self.gridLayout_18.addWidget(self.numero_struttura, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_18.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_18.addWidget(self.label_3, 1, 2, 1, 1)
        self.comboBox_sigla_struttura = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_sigla_struttura.setEnabled(False)
        self.comboBox_sigla_struttura.setMinimumSize(QtCore.QSize(90, 0))
        self.comboBox_sigla_struttura.setMaximumSize(QtCore.QSize(90, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sigla_struttura.setFont(font)
        self.comboBox_sigla_struttura.setEditable(True)
        self.comboBox_sigla_struttura.setObjectName("comboBox_sigla_struttura")
        self.comboBox_sigla_struttura.addItem("")
        self.comboBox_sigla_struttura.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_sigla_struttura, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_18)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_categoria_struttura = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_categoria_struttura.setFont(font)
        self.comboBox_categoria_struttura.setEditable(True)
        self.comboBox_categoria_struttura.setObjectName("comboBox_categoria_struttura")
        self.gridLayout_6.addWidget(self.comboBox_categoria_struttura, 0, 0, 1, 1)
        self.comboBox_tipologia_struttura = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_tipologia_struttura.setFont(font)
        self.comboBox_tipologia_struttura.setEditable(True)
        self.comboBox_tipologia_struttura.setObjectName("comboBox_tipologia_struttura")
        self.gridLayout_6.addWidget(self.comboBox_tipologia_struttura, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 1, 1, 1)
        self.comboBox_definizione_struttura = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_definizione_struttura.setFont(font)
        self.comboBox_definizione_struttura.setEditable(True)
        self.comboBox_definizione_struttura.setObjectName("comboBox_definizione_struttura")
        self.gridLayout_6.addWidget(self.comboBox_definizione_struttura, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget = QtGui.QTabWidget(DialogStruttura)
        self.tabWidget.setGeometry(QtCore.QRect(13, 276, 641, 477))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.textEdit_descrizione_struttura = QtGui.QTextEdit(self.tab)
        self.textEdit_descrizione_struttura.setMinimumSize(QtCore.QSize(500, 150))
        self.textEdit_descrizione_struttura.setMaximumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_struttura.setFont(font)
        self.textEdit_descrizione_struttura.setObjectName("textEdit_descrizione_struttura")
        self.verticalLayout_5.addWidget(self.textEdit_descrizione_struttura)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.textEdit_interpretazione_struttura = QtGui.QTextEdit(self.tab)
        self.textEdit_interpretazione_struttura.setMinimumSize(QtCore.QSize(0, 150))
        self.textEdit_interpretazione_struttura.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione_struttura.setFont(font)
        self.textEdit_interpretazione_struttura.setObjectName("textEdit_interpretazione_struttura")
        self.verticalLayout_5.addWidget(self.textEdit_interpretazione_struttura)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_15.addWidget(self.label_12, 0, 0, 1, 4)
        self.label_37 = QtGui.QLabel(self.tab_2)
        self.label_37.setMinimumSize(QtCore.QSize(0, 15))
        self.label_37.setObjectName("label_37")
        self.gridLayout_15.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 15))
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 1, 3, 1, 1)
        self.comboBox_per_iniz = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_iniz.setObjectName("comboBox_per_iniz")
        self.comboBox_per_iniz.addItem("")
        self.comboBox_per_iniz.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_per_iniz, 3, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_15.addWidget(self.label_32, 4, 4, 1, 1)
        self.comboBox_fas_iniz = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_iniz.setObjectName("comboBox_fas_iniz")
        self.gridLayout_15.addWidget(self.comboBox_fas_iniz, 3, 1, 1, 1)
        self.comboBox_per_fin = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_fin.setObjectName("comboBox_per_fin")
        self.gridLayout_15.addWidget(self.comboBox_per_fin, 3, 3, 1, 1)
        self.comboBox_fas_fin = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_fin.setObjectName("comboBox_fas_fin")
        self.gridLayout_15.addWidget(self.comboBox_fas_fin, 3, 4, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_15)
        self.lineEdit_datazione_estesa = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_datazione_estesa.setObjectName("lineEdit_datazione_estesa")
        self.verticalLayout_8.addWidget(self.lineEdit_datazione_estesa)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_9.addLayout(self.gridLayout_16)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_10.addWidget(self.line_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.pushButton_insert_row_rapporti = QtGui.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_rapporti.setFont(font)
        self.pushButton_insert_row_rapporti.setObjectName("pushButton_insert_row_rapporti")
        self.horizontalLayout_4.addWidget(self.pushButton_insert_row_rapporti)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_14.addLayout(self.verticalLayout_11)
        self.tableWidget_rapporti = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_rapporti.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_rapporti.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_rapporti.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_rapporti.setRowCount(1)
        self.tableWidget_rapporti.setColumnCount(4)
        self.tableWidget_rapporti.setObjectName("tableWidget_rapporti")
        self.tableWidget_rapporti.setColumnCount(4)
        self.tableWidget_rapporti.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(3, item)
        self.verticalLayout_14.addWidget(self.tableWidget_rapporti)
        self.gridLayout_17.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_insert_row_elementi = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_elementi.setGeometry(QtCore.QRect(150, 150, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_elementi.setFont(font)
        self.pushButton_insert_row_elementi.setObjectName("pushButton_insert_row_elementi")
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(27, 157, 121, 17))
        self.label_11.setObjectName("label_11")
        self.tableWidget_elementi_strutturali = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_elementi_strutturali.setGeometry(QtCore.QRect(27, 182, 581, 80))
        self.tableWidget_elementi_strutturali.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_elementi_strutturali.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_elementi_strutturali.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_elementi_strutturali.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_elementi_strutturali.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_elementi_strutturali.setRowCount(1)
        self.tableWidget_elementi_strutturali.setColumnCount(2)
        self.tableWidget_elementi_strutturali.setObjectName("tableWidget_elementi_strutturali")
        self.tableWidget_elementi_strutturali.setColumnCount(2)
        self.tableWidget_elementi_strutturali.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_strutturali.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_strutturali.setHorizontalHeaderItem(1, item)
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(27, 303, 76, 17))
        self.label_15.setObjectName("label_15")
        self.tableWidget_misurazioni = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_misurazioni.setGeometry(QtCore.QRect(27, 328, 581, 80))
        self.tableWidget_misurazioni.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_misurazioni.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_misurazioni.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_misurazioni.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_misurazioni.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_misurazioni.setRowCount(1)
        self.tableWidget_misurazioni.setColumnCount(3)
        self.tableWidget_misurazioni.setObjectName("tableWidget_misurazioni")
        self.tableWidget_misurazioni.setColumnCount(3)
        self.tableWidget_misurazioni.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(2, item)
        self.pushButton_insert_row_misurazioni = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_misurazioni.setGeometry(QtCore.QRect(100, 300, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_misurazioni.setFont(font)
        self.pushButton_insert_row_misurazioni.setObjectName("pushButton_insert_row_misurazioni")
        self.tableWidget_materiali_impiegati = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_materiali_impiegati.setGeometry(QtCore.QRect(30, 30, 581, 101))
        self.tableWidget_materiali_impiegati.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_materiali_impiegati.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_materiali_impiegati.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_materiali_impiegati.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_materiali_impiegati.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_materiali_impiegati.setRowCount(1)
        self.tableWidget_materiali_impiegati.setColumnCount(1)
        self.tableWidget_materiali_impiegati.setObjectName("tableWidget_materiali_impiegati")
        self.tableWidget_materiali_impiegati.setColumnCount(1)
        self.tableWidget_materiali_impiegati.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_materiali_impiegati.setHorizontalHeaderItem(0, item)
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 117, 17))
        self.label_8.setObjectName("label_8")
        self.pushButton_insert_row_materiali = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_materiali.setGeometry(QtCore.QRect(150, 0, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_materiali.setFont(font)
        self.pushButton_insert_row_materiali.setObjectName("pushButton_insert_row_materiali")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(DialogStruttura)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DialogStruttura)

    def retranslateUi(self, DialogStruttura):
        DialogStruttura.setWindowTitle(QtGui.QApplication.translate("DialogStruttura", "pyArchInit Gestione Scavi - Scheda Struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DialogStruttura", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("DialogStruttura", "Reload DB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("DialogStruttura", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("DialogStruttura", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("DialogStruttura", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("DialogStruttura", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("DialogStruttura", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("DialogStruttura", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("DialogStruttura", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DialogStruttura", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("DialogStruttura", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("DialogStruttura", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DialogStruttura", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("DialogStruttura", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogStruttura", "Sito ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogStruttura", "Sigla struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogStruttura", "N°", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigla_struttura.setItemText(0, QtGui.QApplication.translate("DialogStruttura", "Aggiungi un valore...", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigla_struttura.setItemText(1, QtGui.QApplication.translate("DialogStruttura", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogStruttura", "Categoria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogStruttura", "Tipologia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogStruttura", "Definizione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogStruttura", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_struttura.setHtml(QtGui.QApplication.translate("DialogStruttura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogStruttura", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogStruttura", "Interpretazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogStruttura", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DialogStruttura", "Periodizzazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("DialogStruttura", "Iniziale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogStruttura", "Finale ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_per_iniz.setItemText(0, QtGui.QApplication.translate("DialogStruttura", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_per_iniz.setItemText(1, QtGui.QApplication.translate("DialogStruttura", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("DialogStruttura", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogStruttura", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogStruttura", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("DialogStruttura", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DialogStruttura", "Datazione estesa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DialogStruttura", "Rapporti struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_rapporti.setText(QtGui.QApplication.translate("DialogStruttura", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogStruttura", "Tipo di rapporto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogStruttura", "Sito", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogStruttura", "Sigla", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DialogStruttura", "Numero", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogStruttura", "Periodizzazione - Rapporti", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_elementi.setText(QtGui.QApplication.translate("DialogStruttura", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogStruttura", "Elementi strutturali", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_strutturali.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogStruttura", "Tipologia elemnto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_strutturali.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogStruttura", "Quantità", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogStruttura", "Misurazione", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogStruttura", "Tipo misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogStruttura", "Unita\' di misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogStruttura", "Valore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_misurazioni.setText(QtGui.QApplication.translate("DialogStruttura", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_materiali_impiegati.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogStruttura", "Materiali", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogStruttura", "Materiali impiegati", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_materiali.setText(QtGui.QApplication.translate("DialogStruttura", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("DialogStruttura", "Elementi costruttivi", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
