# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_UT_ui.ui'
#
# Created: Wed Jun  6 00:38:32 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogUT(object):
    def setupUi(self, DialogUT):
        DialogUT.setObjectName("DialogUT")
        DialogUT.resize(576, 829)
        DialogUT.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/iconPAI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogUT.setWindowIcon(icon)
        self.gridLayout_18 = QtGui.QGridLayout(DialogUT)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(-1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(DialogUT)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_first_rec = QtGui.QPushButton(DialogUT)
        self.pushButton_first_rec.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/5_leftArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName("pushButton_first_rec")
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 0, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogUT)
        self.pushButton_prev_rec.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/4_leftArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon2)
        self.pushButton_prev_rec.setObjectName("pushButton_prev_rec")
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 1, 1, 2)
        self.pushButton_next_rec = QtGui.QPushButton(DialogUT)
        self.pushButton_next_rec.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/6_rightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon3)
        self.pushButton_next_rec.setObjectName("pushButton_next_rec")
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(DialogUT)
        self.pushButton_last_rec.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/7_rightArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon4)
        self.pushButton_last_rec.setObjectName("pushButton_last_rec")
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/newrec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon5)
        self.pushButton_new_rec.setObjectName("pushButton_new_rec")
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/b_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon6)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon7)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(70, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/new_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName("pushButton_new_search")
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon9)
        self.pushButton_search_go.setObjectName("pushButton_search_go")
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon10)
        self.pushButton_sort.setObjectName("pushButton_sort")
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/view_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon11)
        self.pushButton_view_all.setObjectName("pushButton_view_all")
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(DialogUT)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_42 = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_43 = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogUT)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName("label_status")
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText("")
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName("label_sort")
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName("label_rec_corrente")
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(DialogUT)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName("label_rec_tot")
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_8 = QtGui.QFrame(DialogUT)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_progetto = QtGui.QComboBox(DialogUT)
        self.comboBox_progetto.setEnabled(False)
        self.comboBox_progetto.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_progetto.setFont(font)
        self.comboBox_progetto.setMouseTracking(True)
        self.comboBox_progetto.setEditable(True)
        self.comboBox_progetto.setMaxVisibleItems(99999)
        self.comboBox_progetto.setMaxCount(2147483647)
        self.comboBox_progetto.setObjectName("comboBox_progetto")
        self.comboBox_progetto.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_progetto)
        self.comboBox_nr_ut = QtGui.QComboBox(DialogUT)
        self.comboBox_nr_ut.setEnabled(False)
        self.comboBox_nr_ut.setMaximumSize(QtCore.QSize(64, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_nr_ut.setFont(font)
        self.comboBox_nr_ut.setEditable(True)
        self.comboBox_nr_ut.setObjectName("comboBox_nr_ut")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.comboBox_nr_ut.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_nr_ut)
        self.lineEdit_ut_letterale = QtGui.QLineEdit(DialogUT)
        self.lineEdit_ut_letterale.setEnabled(False)
        self.lineEdit_ut_letterale.setMinimumSize(QtCore.QSize(61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_ut_letterale.setFont(font)
        self.lineEdit_ut_letterale.setObjectName("lineEdit_ut_letterale")
        self.horizontalLayout_2.addWidget(self.lineEdit_ut_letterale)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(DialogUT)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(303, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(DialogUT)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_3 = QtGui.QLabel(DialogUT)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.gridLayout_10.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget_ut = QtGui.QTabWidget(DialogUT)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_ut.setFont(font)
        self.tabWidget_ut.setObjectName("tabWidget_ut")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.textEdit_descrizione_ut = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_ut.setFont(font)
        self.textEdit_descrizione_ut.setObjectName("textEdit_descrizione_ut")
        self.verticalLayout_5.addWidget(self.textEdit_descrizione_ut)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.textEdit_interpretazione_ut = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione_ut.setFont(font)
        self.textEdit_interpretazione_ut.setObjectName("textEdit_interpretazione_ut")
        self.verticalLayout_5.addWidget(self.textEdit_interpretazione_ut)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        self.lineEdit_def_ut = QtGui.QLineEdit(self.tab)
        self.lineEdit_def_ut.setObjectName("lineEdit_def_ut")
        self.gridLayout_7.addWidget(self.lineEdit_def_ut, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.tabWidget_ut.addTab(self.tab, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.comboBox_nazione = QtGui.QComboBox(self.tab_6)
        self.comboBox_nazione.setEditable(True)
        self.comboBox_nazione.setObjectName("comboBox_nazione")
        self.gridLayout_20.addWidget(self.comboBox_nazione, 1, 0, 1, 1)
        self.comboBox_regione = QtGui.QComboBox(self.tab_6)
        self.comboBox_regione.setEditable(True)
        self.comboBox_regione.setObjectName("comboBox_regione")
        self.gridLayout_20.addWidget(self.comboBox_regione, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_20.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_20.addWidget(self.label_48, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_20.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_20)
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.comboBox_provincia = QtGui.QComboBox(self.tab_6)
        self.comboBox_provincia.setEditable(True)
        self.comboBox_provincia.setObjectName("comboBox_provincia")
        self.gridLayout_22.addWidget(self.comboBox_provincia, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_22.addWidget(self.label_11, 1, 0, 1, 1)
        self.comboBox_comune = QtGui.QComboBox(self.tab_6)
        self.comboBox_comune.setEditable(True)
        self.comboBox_comune.setObjectName("comboBox_comune")
        self.gridLayout_22.addWidget(self.comboBox_comune, 2, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_22.addWidget(self.label_15, 3, 0, 1, 1)
        self.comboBox_frazione = QtGui.QComboBox(self.tab_6)
        self.comboBox_frazione.setEditable(True)
        self.comboBox_frazione.setObjectName("comboBox_frazione")
        self.gridLayout_22.addWidget(self.comboBox_frazione, 4, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_22.addWidget(self.label_30, 5, 0, 1, 1)
        self.comboBox_localita = QtGui.QComboBox(self.tab_6)
        self.comboBox_localita.setEditable(True)
        self.comboBox_localita.setObjectName("comboBox_localita")
        self.gridLayout_22.addWidget(self.comboBox_localita, 6, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_22.addWidget(self.label_31, 7, 0, 1, 1)
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.lineEdit_indirizzo = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_indirizzo.setMinimumSize(QtCore.QSize(490, 0))
        self.lineEdit_indirizzo.setObjectName("lineEdit_indirizzo")
        self.gridLayout_21.addWidget(self.lineEdit_indirizzo, 0, 0, 1, 1)
        self.lineEdit_nr_civico = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_nr_civico.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_nr_civico.setText("")
        self.lineEdit_nr_civico.setObjectName("lineEdit_nr_civico")
        self.gridLayout_21.addWidget(self.lineEdit_nr_civico, 0, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_21.addWidget(self.label_49, 1, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_21.addWidget(self.label_50, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem4, 2, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 8, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_22)
        self.gridLayout_23.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget_ut.addTab(self.tab_6, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 0, 0, 1, 4)
        self.lineEdit_carta_topo_igm = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_carta_topo_igm.setObjectName("lineEdit_carta_topo_igm")
        self.gridLayout_13.addWidget(self.lineEdit_carta_topo_igm, 1, 1, 1, 1)
        self.lineEdit_carta_ctr = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_carta_ctr.setObjectName("lineEdit_carta_ctr")
        self.gridLayout_13.addWidget(self.lineEdit_carta_ctr, 1, 2, 1, 2)
        self.lineEdit_foglio_catastale = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_foglio_catastale.setObjectName("lineEdit_foglio_catastale")
        self.gridLayout_13.addWidget(self.lineEdit_foglio_catastale, 1, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_13.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 2, 2, 1, 3)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_13.addWidget(self.label_16, 2, 5, 1, 1)
        self.lineEdit_coord_geografiche = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_coord_geografiche.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_coord_geografiche.setFont(font)
        self.lineEdit_coord_geografiche.setObjectName("lineEdit_coord_geografiche")
        self.gridLayout_13.addWidget(self.lineEdit_coord_geografiche, 3, 1, 1, 1)
        self.lineEdit_coord_piane = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_coord_piane.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_coord_piane.setFont(font)
        self.lineEdit_coord_piane.setText("")
        self.lineEdit_coord_piane.setObjectName("lineEdit_coord_piane")
        self.gridLayout_13.addWidget(self.lineEdit_coord_piane, 3, 2, 1, 2)
        self.lineEdit_quota = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_quota.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_quota.setFont(font)
        self.lineEdit_quota.setText("")
        self.lineEdit_quota.setObjectName("lineEdit_quota")
        self.gridLayout_13.addWidget(self.lineEdit_quota, 3, 5, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_13.addWidget(self.line_2, 8, 0, 2, 6)
        self.label_17 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_13.addWidget(self.label_17, 9, 1, 1, 3)
        self.lineEdit_andamento_terreno_pendenza = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_andamento_terreno_pendenza.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_andamento_terreno_pendenza.setFont(font)
        self.lineEdit_andamento_terreno_pendenza.setObjectName("lineEdit_andamento_terreno_pendenza")
        self.gridLayout_13.addWidget(self.lineEdit_andamento_terreno_pendenza, 10, 1, 1, 1)
        self.lineEdit_utilizzo_suolo_vegetazione = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_utilizzo_suolo_vegetazione.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_utilizzo_suolo_vegetazione.setFont(font)
        self.lineEdit_utilizzo_suolo_vegetazione.setText("")
        self.lineEdit_utilizzo_suolo_vegetazione.setObjectName("lineEdit_utilizzo_suolo_vegetazione")
        self.gridLayout_13.addWidget(self.lineEdit_utilizzo_suolo_vegetazione, 10, 2, 1, 2)
        self.textEdit_descrizione_empirica_suolo = QtGui.QTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_empirica_suolo.setFont(font)
        self.textEdit_descrizione_empirica_suolo.setObjectName("textEdit_descrizione_empirica_suolo")
        self.gridLayout_13.addWidget(self.textEdit_descrizione_empirica_suolo, 10, 4, 3, 2)
        self.textEdit_descrizione_luogo = QtGui.QTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_luogo.setFont(font)
        self.textEdit_descrizione_luogo.setObjectName("textEdit_descrizione_luogo")
        self.gridLayout_13.addWidget(self.textEdit_descrizione_luogo, 14, 1, 1, 3)
        self.label_37 = QtGui.QLabel(self.tab_2)
        self.label_37.setMinimumSize(QtCore.QSize(0, 15))
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.gridLayout_13.addWidget(self.label_37, 15, 1, 1, 1)
        self.lineEdit_metodo_rilievo_e_ricognizione = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_metodo_rilievo_e_ricognizione.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_metodo_rilievo_e_ricognizione.setFont(font)
        self.lineEdit_metodo_rilievo_e_ricognizione.setObjectName("lineEdit_metodo_rilievo_e_ricognizione")
        self.gridLayout_13.addWidget(self.lineEdit_metodo_rilievo_e_ricognizione, 16, 1, 1, 2)
        self.lineEdit_geometria = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_geometria.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_geometria.setFont(font)
        self.lineEdit_geometria.setObjectName("lineEdit_geometria")
        self.gridLayout_13.addWidget(self.lineEdit_geometria, 16, 3, 1, 3)
        self.label_51 = QtGui.QLabel(self.tab_2)
        self.label_51.setMinimumSize(QtCore.QSize(0, 15))
        self.label_51.setWordWrap(True)
        self.label_51.setObjectName("label_51")
        self.gridLayout_13.addWidget(self.label_51, 17, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.tab_2)
        self.label_52.setMinimumSize(QtCore.QSize(0, 15))
        self.label_52.setWordWrap(True)
        self.label_52.setObjectName("label_52")
        self.gridLayout_13.addWidget(self.label_52, 17, 3, 1, 3)
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setMinimumSize(QtCore.QSize(0, 15))
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 11, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setMinimumSize(QtCore.QSize(0, 15))
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.gridLayout_13.addWidget(self.label_32, 11, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setMinimumSize(QtCore.QSize(0, 15))
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.gridLayout_13.addWidget(self.label_33, 13, 4, 1, 2)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setMinimumSize(QtCore.QSize(0, 15))
        self.label_18.setObjectName("label_18")
        self.gridLayout_13.addWidget(self.label_18, 4, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setMinimumSize(QtCore.QSize(0, 15))
        self.label_19.setObjectName("label_19")
        self.gridLayout_13.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setMinimumSize(QtCore.QSize(0, 15))
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 4, 5, 1, 1)
        self.tabWidget_ut.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_56 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_12.addWidget(self.label_56, 0, 0, 1, 3)
        self.lineEdit_data = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.gridLayout_12.addWidget(self.lineEdit_data, 1, 0, 1, 1)
        self.lineEdit_ora_meteo = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_ora_meteo.setObjectName("lineEdit_ora_meteo")
        self.gridLayout_12.addWidget(self.lineEdit_ora_meteo, 1, 1, 1, 2)
        self.lineEdit_responsabile = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_responsabile.setObjectName("lineEdit_responsabile")
        self.gridLayout_12.addWidget(self.lineEdit_responsabile, 1, 3, 1, 2)
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 2, 1, 1, 2)
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 2, 3, 1, 2)
        self.lineEdit_dimensioni_ut = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_dimensioni_ut.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_dimensioni_ut.setFont(font)
        self.lineEdit_dimensioni_ut.setObjectName("lineEdit_dimensioni_ut")
        self.gridLayout_12.addWidget(self.lineEdit_dimensioni_ut, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setMinimumSize(QtCore.QSize(0, 15))
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 4, 0, 1, 1)
        self.lineEdit_rep_per_mq = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_rep_per_mq.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_rep_per_mq.setFont(font)
        self.lineEdit_rep_per_mq.setObjectName("lineEdit_rep_per_mq")
        self.gridLayout_12.addWidget(self.lineEdit_rep_per_mq, 5, 0, 1, 1)
        self.lineEdit_rep_datanti = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_rep_datanti.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_rep_datanti.setFont(font)
        self.lineEdit_rep_datanti.setText("")
        self.lineEdit_rep_datanti.setObjectName("lineEdit_rep_datanti")
        self.gridLayout_12.addWidget(self.lineEdit_rep_datanti, 5, 1, 1, 2)
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setMinimumSize(QtCore.QSize(0, 15))
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 6, 0, 1, 1)
        self.label_54 = QtGui.QLabel(self.tab_3)
        self.label_54.setMinimumSize(QtCore.QSize(0, 15))
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.gridLayout_12.addWidget(self.label_54, 6, 1, 1, 2)
        self.lineEdit_periodo_I = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_periodo_I.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_periodo_I.setFont(font)
        self.lineEdit_periodo_I.setObjectName("lineEdit_periodo_I")
        self.gridLayout_12.addWidget(self.lineEdit_periodo_I, 7, 0, 1, 2)
        self.lineEdit_datazione_I = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_datazione_I.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_datazione_I.setFont(font)
        self.lineEdit_datazione_I.setObjectName("lineEdit_datazione_I")
        self.gridLayout_12.addWidget(self.lineEdit_datazione_I, 7, 2, 1, 2)
        self.lineEdit_interpretazione_I = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_interpretazione_I.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_interpretazione_I.setFont(font)
        self.lineEdit_interpretazione_I.setObjectName("lineEdit_interpretazione_I")
        self.gridLayout_12.addWidget(self.lineEdit_interpretazione_I, 7, 4, 1, 1)
        self.label_57 = QtGui.QLabel(self.tab_3)
        self.label_57.setMinimumSize(QtCore.QSize(0, 15))
        self.label_57.setWordWrap(True)
        self.label_57.setObjectName("label_57")
        self.gridLayout_12.addWidget(self.label_57, 8, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.tab_3)
        self.label_53.setMinimumSize(QtCore.QSize(0, 15))
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.gridLayout_12.addWidget(self.label_53, 8, 2, 1, 2)
        self.label_55 = QtGui.QLabel(self.tab_3)
        self.label_55.setMinimumSize(QtCore.QSize(0, 15))
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.gridLayout_12.addWidget(self.label_55, 8, 4, 1, 1)
        self.lineEdit_periodo_II = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_periodo_II.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_periodo_II.setFont(font)
        self.lineEdit_periodo_II.setObjectName("lineEdit_periodo_II")
        self.gridLayout_12.addWidget(self.lineEdit_periodo_II, 9, 0, 1, 2)
        self.lineEdit_datazione_II = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_datazione_II.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_datazione_II.setFont(font)
        self.lineEdit_datazione_II.setObjectName("lineEdit_datazione_II")
        self.gridLayout_12.addWidget(self.lineEdit_datazione_II, 9, 2, 1, 2)
        self.lineEdit_interpretazione_II = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_interpretazione_II.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_interpretazione_II.setFont(font)
        self.lineEdit_interpretazione_II.setObjectName("lineEdit_interpretazione_II")
        self.gridLayout_12.addWidget(self.lineEdit_interpretazione_II, 9, 4, 1, 1)
        self.label_59 = QtGui.QLabel(self.tab_3)
        self.label_59.setMinimumSize(QtCore.QSize(0, 15))
        self.label_59.setWordWrap(True)
        self.label_59.setObjectName("label_59")
        self.gridLayout_12.addWidget(self.label_59, 10, 0, 1, 1)
        self.label_60 = QtGui.QLabel(self.tab_3)
        self.label_60.setMinimumSize(QtCore.QSize(0, 15))
        self.label_60.setWordWrap(True)
        self.label_60.setObjectName("label_60")
        self.gridLayout_12.addWidget(self.label_60, 10, 2, 1, 2)
        self.label_58 = QtGui.QLabel(self.tab_3)
        self.label_58.setMinimumSize(QtCore.QSize(0, 15))
        self.label_58.setWordWrap(True)
        self.label_58.setObjectName("label_58")
        self.gridLayout_12.addWidget(self.label_58, 10, 4, 1, 1)
        self.lineEdit_enti_tutela_vincoli = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_enti_tutela_vincoli.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_enti_tutela_vincoli.setFont(font)
        self.lineEdit_enti_tutela_vincoli.setObjectName("lineEdit_enti_tutela_vincoli")
        self.gridLayout_12.addWidget(self.lineEdit_enti_tutela_vincoli, 11, 0, 1, 2)
        self.label_61 = QtGui.QLabel(self.tab_3)
        self.label_61.setMinimumSize(QtCore.QSize(0, 15))
        self.label_61.setWordWrap(True)
        self.label_61.setObjectName("label_61")
        self.gridLayout_12.addWidget(self.label_61, 12, 0, 1, 1)
        self.lineEdit_indagini_preliminari = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_indagini_preliminari.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_indagini_preliminari.setFont(font)
        self.lineEdit_indagini_preliminari.setObjectName("lineEdit_indagini_preliminari")
        self.gridLayout_12.addWidget(self.lineEdit_indagini_preliminari, 13, 0, 1, 2)
        self.label_62 = QtGui.QLabel(self.tab_3)
        self.label_62.setMinimumSize(QtCore.QSize(0, 15))
        self.label_62.setWordWrap(True)
        self.label_62.setObjectName("label_62")
        self.gridLayout_12.addWidget(self.label_62, 14, 0, 1, 2)
        self.tabWidget_ut.addTab(self.tab_3, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_insert_row_documentazione = QtGui.QPushButton(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_documentazione.setFont(font)
        self.pushButton_insert_row_documentazione.setObjectName("pushButton_insert_row_documentazione")
        self.horizontalLayout_6.addWidget(self.pushButton_insert_row_documentazione)
        self.pushButton_remove_row_documentazione = QtGui.QPushButton(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_documentazione.setFont(font)
        self.pushButton_remove_row_documentazione.setObjectName("pushButton_remove_row_documentazione")
        self.horizontalLayout_6.addWidget(self.pushButton_remove_row_documentazione)
        self.gridLayout_11.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(289, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 0, 1, 1, 1)
        self.tableWidget_documentazione = QtGui.QTableWidget(self.tab_7)
        self.tableWidget_documentazione.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_documentazione.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_documentazione.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_documentazione.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_documentazione.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_documentazione.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_documentazione.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_documentazione.setRowCount(1)
        self.tableWidget_documentazione.setColumnCount(2)
        self.tableWidget_documentazione.setObjectName("tableWidget_documentazione")
        self.tableWidget_documentazione.setColumnCount(2)
        self.tableWidget_documentazione.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_documentazione.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_documentazione.setHorizontalHeaderItem(1, item)
        self.gridLayout_11.addWidget(self.tableWidget_documentazione, 1, 0, 1, 2)
        self.tabWidget_ut.addTab(self.tab_7, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_insert_row_bibliografia = QtGui.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_bibliografia.setFont(font)
        self.pushButton_insert_row_bibliografia.setObjectName("pushButton_insert_row_bibliografia")
        self.horizontalLayout_5.addWidget(self.pushButton_insert_row_bibliografia)
        self.pushButton_remove_row_bibliografia = QtGui.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_bibliografia.setFont(font)
        self.pushButton_remove_row_bibliografia.setObjectName("pushButton_remove_row_bibliografia")
        self.horizontalLayout_5.addWidget(self.pushButton_remove_row_bibliografia)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(305, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 1, 1, 1)
        self.tableWidget_bibliografia = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_bibliografia.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_bibliografia.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_bibliografia.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_bibliografia.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_bibliografia.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_bibliografia.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_bibliografia.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_bibliografia.setRowCount(1)
        self.tableWidget_bibliografia.setColumnCount(1)
        self.tableWidget_bibliografia.setObjectName("tableWidget_bibliografia")
        self.tableWidget_bibliografia.setColumnCount(1)
        self.tableWidget_bibliografia.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_bibliografia.setHorizontalHeaderItem(0, item)
        self.tableWidget_bibliografia.horizontalHeader().setDefaultSectionSize(400)
        self.gridLayout_9.addWidget(self.tableWidget_bibliografia, 1, 0, 1, 2)
        self.tabWidget_ut.addTab(self.tab_5, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_36 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 1, 3, 1, 2)
        self.pushButton_crea_codice_periodo = QtGui.QPushButton(self.tab_4)
        self.pushButton_crea_codice_periodo.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_crea_codice_periodo.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/sheet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_crea_codice_periodo.setIcon(icon12)
        self.pushButton_crea_codice_periodo.setObjectName("pushButton_crea_codice_periodo")
        self.gridLayout_8.addWidget(self.pushButton_crea_codice_periodo, 2, 0, 1, 2)
        self.pushButton_orderLayers = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_orderLayers.setFont(font)
        self.pushButton_orderLayers.setObjectName("pushButton_orderLayers")
        self.gridLayout_8.addWidget(self.pushButton_orderLayers, 2, 2, 1, 1)
        self.pushButton_export_matrix = QtGui.QPushButton(self.tab_4)
        self.pushButton_export_matrix.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_export_matrix.setFont(font)
        self.pushButton_export_matrix.setIcon(icon12)
        self.pushButton_export_matrix.setObjectName("pushButton_export_matrix")
        self.gridLayout_8.addWidget(self.pushButton_export_matrix, 2, 3, 1, 3)
        self.lineEdit_codice_periodo = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_codice_periodo.setEnabled(False)
        self.lineEdit_codice_periodo.setObjectName("lineEdit_codice_periodo")
        self.gridLayout_8.addWidget(self.lineEdit_codice_periodo, 3, 0, 1, 1)
        self.lineEditOrderLayer = QtGui.QLineEdit(self.tab_4)
        self.lineEditOrderLayer.setEnabled(False)
        self.lineEditOrderLayer.setObjectName("lineEditOrderLayer")
        self.gridLayout_8.addWidget(self.lineEditOrderLayer, 3, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_8.addWidget(self.label_38, 4, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 4, 2, 1, 1)
        self.label_39 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 4, 3, 1, 3)
        self.toolButtonGis = QtGui.QToolButton(self.tab_4)
        self.toolButtonGis.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonGis.setToolTip("")
        self.toolButtonGis.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/GIS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGis.setIcon(icon13)
        self.toolButtonGis.setCheckable(True)
        self.toolButtonGis.setChecked(False)
        self.toolButtonGis.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonGis.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonGis.setObjectName("toolButtonGis")
        self.gridLayout_8.addWidget(self.toolButtonGis, 5, 0, 1, 1)
        self.pushButton_showLayer = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showLayer.setFont(font)
        self.pushButton_showLayer.setIcon(icon12)
        self.pushButton_showLayer.setObjectName("pushButton_showLayer")
        self.gridLayout_8.addWidget(self.pushButton_showLayer, 5, 2, 1, 1)
        self.toolButtonPreview = QtGui.QToolButton(self.tab_4)
        self.toolButtonPreview.setToolTip("")
        self.toolButtonPreview.setIcon(icon13)
        self.toolButtonPreview.setCheckable(True)
        self.toolButtonPreview.setChecked(False)
        self.toolButtonPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPreview.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPreview.setObjectName("toolButtonPreview")
        self.gridLayout_8.addWidget(self.toolButtonPreview, 5, 3, 1, 2)
        self.toolButtonPan = QtGui.QToolButton(self.tab_4)
        self.toolButtonPan.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonPan.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/mActionPan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPan.setIcon(icon14)
        self.toolButtonPan.setCheckable(True)
        self.toolButtonPan.setChecked(False)
        self.toolButtonPan.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPan.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPan.setObjectName("toolButtonPan")
        self.gridLayout_8.addWidget(self.toolButtonPan, 5, 5, 1, 1)
        self.label_40 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_8.addWidget(self.label_40, 6, 0, 1, 3)
        self.pushButton_showSelectedFeatures = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showSelectedFeatures.setFont(font)
        self.pushButton_showSelectedFeatures.setIcon(icon12)
        self.pushButton_showSelectedFeatures.setObjectName("pushButton_showSelectedFeatures")
        self.gridLayout_8.addWidget(self.pushButton_showSelectedFeatures, 7, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 8, 0, 1, 1)
        self.pushButton_pdf_exp = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pdf_exp.setFont(font)
        self.pushButton_pdf_exp.setIcon(icon12)
        self.pushButton_pdf_exp.setObjectName("pushButton_pdf_exp")
        self.gridLayout_8.addWidget(self.pushButton_pdf_exp, 9, 0, 1, 1)
        self.pushButton_exp_index_us = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exp_index_us.setFont(font)
        self.pushButton_exp_index_us.setIcon(icon12)
        self.pushButton_exp_index_us.setObjectName("pushButton_exp_index_us")
        self.gridLayout_8.addWidget(self.pushButton_exp_index_us, 9, 1, 1, 2)
        self.label_44 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 10, 0, 1, 1)
        self.toolButtonPreviewMedia = QtGui.QToolButton(self.tab_4)
        self.toolButtonPreviewMedia.setMinimumSize(QtCore.QSize(109, 0))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/photo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPreviewMedia.setIcon(icon15)
        self.toolButtonPreviewMedia.setCheckable(True)
        self.toolButtonPreviewMedia.setObjectName("toolButtonPreviewMedia")
        self.gridLayout_8.addWidget(self.toolButtonPreviewMedia, 11, 0, 1, 1)
        self.label_70 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_8.addWidget(self.label_70, 12, 0, 1, 3)
        self.comboBox_sito_rappcheck = QtGui.QComboBox(self.tab_4)
        self.comboBox_sito_rappcheck.setEnabled(True)
        self.comboBox_sito_rappcheck.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito_rappcheck.setFont(font)
        self.comboBox_sito_rappcheck.setMouseTracking(True)
        self.comboBox_sito_rappcheck.setEditable(False)
        self.comboBox_sito_rappcheck.setMaxVisibleItems(99999)
        self.comboBox_sito_rappcheck.setMaxCount(2147483647)
        self.comboBox_sito_rappcheck.setObjectName("comboBox_sito_rappcheck")
        self.comboBox_sito_rappcheck.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_sito_rappcheck, 13, 0, 1, 4)
        self.pushButton_rapp_check = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rapp_check.setFont(font)
        self.pushButton_rapp_check.setIcon(icon12)
        self.pushButton_rapp_check.setObjectName("pushButton_rapp_check")
        self.gridLayout_8.addWidget(self.pushButton_rapp_check, 13, 4, 1, 2)
        self.tabWidget_ut.addTab(self.tab_4, "")
        self.gridLayout_10.addWidget(self.tabWidget_ut, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_10, 0, 1, 1, 1)

        self.retranslateUi(DialogUT)
        self.tabWidget_ut.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogUT)

    def retranslateUi(self, DialogUT):
        DialogUT.setWindowTitle(QtGui.QApplication.translate("DialogUT", "pyArchInit Archeologia del Territorio- Scheda UT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DialogUT", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("DialogUT", "Reload DB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("DialogUT", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("DialogUT", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("DialogUT", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("DialogUT", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("DialogUT", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("DialogUT", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("DialogUT", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("DialogUT", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("DialogUT", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("DialogUT", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("DialogUT", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("DialogUT", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("DialogUT", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DialogUT", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("DialogUT", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("DialogUT", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DialogUT", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("DialogUT", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_progetto.setItemText(0, QtGui.QApplication.translate("DialogUT", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(0, QtGui.QApplication.translate("DialogUT", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(1, QtGui.QApplication.translate("DialogUT", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(2, QtGui.QApplication.translate("DialogUT", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(3, QtGui.QApplication.translate("DialogUT", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(4, QtGui.QApplication.translate("DialogUT", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(5, QtGui.QApplication.translate("DialogUT", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(6, QtGui.QApplication.translate("DialogUT", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(7, QtGui.QApplication.translate("DialogUT", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(8, QtGui.QApplication.translate("DialogUT", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(9, QtGui.QApplication.translate("DialogUT", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(10, QtGui.QApplication.translate("DialogUT", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(11, QtGui.QApplication.translate("DialogUT", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(12, QtGui.QApplication.translate("DialogUT", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(13, QtGui.QApplication.translate("DialogUT", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(14, QtGui.QApplication.translate("DialogUT", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(15, QtGui.QApplication.translate("DialogUT", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(16, QtGui.QApplication.translate("DialogUT", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(17, QtGui.QApplication.translate("DialogUT", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(18, QtGui.QApplication.translate("DialogUT", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nr_ut.setItemText(19, QtGui.QApplication.translate("DialogUT", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogUT", "Progetto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogUT", "UT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogUT", "UTabc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogUT", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_ut.setHtml(QtGui.QApplication.translate("DialogUT", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogUT", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogUT", "Interpretazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogUT", "Definizione UT", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_ut.setTabText(self.tabWidget_ut.indexOf(self.tab), QtGui.QApplication.translate("DialogUT", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogUT", "Nazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("DialogUT", "Regione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogUT", "Localizzazione non georeferenziata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogUT", "Provincia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogUT", "Comune", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("DialogUT", "Frazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("DialogUT", "Localita\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("DialogUT", "Indirizzo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("DialogUT", "nr civico", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_ut.setTabText(self.tabWidget_ut.indexOf(self.tab_6), QtGui.QApplication.translate("DialogUT", "Localizzazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DialogUT", "Localizzazione georeferenziata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogUT", "Carta topografica IGM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogUT", "Carta CTR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogUT", "Foglio catastale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DialogUT", "Descrizione sito", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_empirica_suolo.setHtml(QtGui.QApplication.translate("DialogUT", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_luogo.setHtml(QtGui.QApplication.translate("DialogUT", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("DialogUT", "Descrizione  luogo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("DialogUT", "Rilievo e Ricognizione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("DialogUT", "Geometria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("DialogUT", "Andamento terreno/pendenza", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("DialogUT", "Utilizzo suolo/Vegetazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("DialogUT", "Descrizione empirica del suolo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("DialogUT", "Coord. Geografiche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DialogUT", "Coord. Piane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("DialogUT", "Quota", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_ut.setTabText(self.tabWidget_ut.indexOf(self.tab_2), QtGui.QApplication.translate("DialogUT", "Loc. georef", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("DialogUT", "Dati UT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("DialogUT", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("DialogUT", "Ora/meteo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("DialogUT", "Responsabile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("DialogUT", "Dimensioni UT (mq)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("DialogUT", "Reperti per mq", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("DialogUT", "lineEdit_rep_datanti", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("DialogUT", "Periodo I", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("DialogUT", "Datazione I", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("DialogUT", "Intepretazione I", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("DialogUT", "Periodo II", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("DialogUT", "Datazione II", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("DialogUT", "Intepretazione II", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("DialogUT", "Enti tutela e vincoli", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("DialogUT", "Indagini preliminari", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_ut.setTabText(self.tabWidget_ut.indexOf(self.tab_3), QtGui.QApplication.translate("DialogUT", "Dati UT", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_documentazione.setText(QtGui.QApplication.translate("DialogUT", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_documentazione.setText(QtGui.QApplication.translate("DialogUT", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_documentazione.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogUT", "Tipo documentazione", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_documentazione.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogUT", "Riferimenti", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_ut.setTabText(self.tabWidget_ut.indexOf(self.tab_7), QtGui.QApplication.translate("DialogUT", "Documentazione", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_bibliografia.setText(QtGui.QApplication.translate("DialogUT", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_bibliografia.setText(QtGui.QApplication.translate("DialogUT", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_bibliografia.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogUT", "Riferimenti bibliografici", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_ut.setTabText(self.tabWidget_ut.indexOf(self.tab_5), QtGui.QApplication.translate("DialogUT", "Bibliografia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("DialogUT", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("DialogUT", "Crea Codice Periodo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("DialogUT", "Esporta Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_crea_codice_periodo.setToolTip(QtGui.QApplication.translate("DialogUT", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_crea_codice_periodo.setText(QtGui.QApplication.translate("DialogUT", "Crea codice periodo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_orderLayers.setText(QtGui.QApplication.translate("DialogUT", "Ordine Stratigrafico", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export_matrix.setToolTip(QtGui.QApplication.translate("DialogUT", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export_matrix.setText(QtGui.QApplication.translate("DialogUT", "export Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("DialogUT", "Visualizzazione GIS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("DialogUT", "Visualizza US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("DialogUT", "Attivazione Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGis.setShortcut(QtGui.QApplication.translate("DialogUT", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showLayer.setToolTip(QtGui.QApplication.translate("DialogUT", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showLayer.setText(QtGui.QApplication.translate("DialogUT", "Visualizza US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setText(QtGui.QApplication.translate("DialogUT", "Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setShortcut(QtGui.QApplication.translate("DialogUT", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setToolTip(QtGui.QApplication.translate("DialogUT", "Pan tool", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setShortcut(QtGui.QApplication.translate("DialogUT", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("DialogUT", "Apri schede US selezionate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setToolTip(QtGui.QApplication.translate("DialogUT", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setText(QtGui.QApplication.translate("DialogUT", "apri schede US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("DialogUT", "Esportazioni PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setToolTip(QtGui.QApplication.translate("DialogUT", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setText(QtGui.QApplication.translate("DialogUT", "Singole schede US", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exp_index_us.setText(QtGui.QApplication.translate("DialogUT", "Elenco US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("DialogUT", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreviewMedia.setText(QtGui.QApplication.translate("DialogUT", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("DialogUT", "Controlla rapporti stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito_rappcheck.setItemText(0, QtGui.QApplication.translate("DialogUT", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rapp_check.setToolTip(QtGui.QApplication.translate("DialogUT", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rapp_check.setText(QtGui.QApplication.translate("DialogUT", "Check, go!!!!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_ut.setTabText(self.tabWidget_ut.indexOf(self.tab_4), QtGui.QApplication.translate("DialogUT", "Tools", None, QtGui.QApplication.UnicodeUTF8))

