# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_inventario_reperti_ui.ui'
#
# Created: Sun Dec 16 17:15:35 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogInventarioMateriali(object):
    def setupUi(self, DialogInventarioMateriali):
        DialogInventarioMateriali.setObjectName(_fromUtf8("DialogInventarioMateriali"))
        DialogInventarioMateriali.resize(697, 644)
        DialogInventarioMateriali.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/finds.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogInventarioMateriali.setWindowIcon(icon)
        self.gridLayout_18 = QtGui.QGridLayout(DialogInventarioMateriali)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_29 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(DialogInventarioMateriali)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_first_rec = QtGui.QPushButton(DialogInventarioMateriali)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 0, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogInventarioMateriali)
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon2)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 1, 1, 2)
        self.pushButton_next_rec = QtGui.QPushButton(DialogInventarioMateriali)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon3)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(DialogInventarioMateriali)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon4)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon5)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon6)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon7)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout.addWidget(self.pushButton_delete, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(70, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon9)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon10)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon11)
        self.pushButton_view_all.setObjectName(_fromUtf8("pushButton_view_all"))
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(DialogInventarioMateriali)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_42 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_43 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogInventarioMateriali)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText(_fromUtf8(""))
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_27 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName(_fromUtf8("label_rec_corrente"))
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName(_fromUtf8("label_rec_tot"))
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.line_8 = QtGui.QFrame(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_6.addWidget(self.line_8, 0, 0, 1, 3)
        self.comboBox_sito = QtGui.QComboBox(DialogInventarioMateriali)
        self.comboBox_sito.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setFrame(False)
        self.comboBox_sito.setObjectName(_fromUtf8("comboBox_sito"))
        self.comboBox_sito.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_sito, 1, 0, 1, 2)
        self.lineEdit_num_inv = QtGui.QLineEdit(DialogInventarioMateriali)
        self.lineEdit_num_inv.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num_inv.setFont(font)
        self.lineEdit_num_inv.setObjectName(_fromUtf8("lineEdit_num_inv"))
        self.gridLayout_6.addWidget(self.lineEdit_num_inv, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 2, 1, 1, 1)
        self.label = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 4, 1, 1, 1)
        self.comboBox_tipo_reperto = QtGui.QComboBox(DialogInventarioMateriali)
        self.comboBox_tipo_reperto.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_tipo_reperto.setFont(font)
        self.comboBox_tipo_reperto.setMouseTracking(True)
        self.comboBox_tipo_reperto.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_tipo_reperto.setEditable(True)
        self.comboBox_tipo_reperto.setMaxVisibleItems(99999)
        self.comboBox_tipo_reperto.setMaxCount(2147483647)
        self.comboBox_tipo_reperto.setFrame(False)
        self.comboBox_tipo_reperto.setObjectName(_fromUtf8("comboBox_tipo_reperto"))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.comboBox_tipo_reperto.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_tipo_reperto, 3, 1, 1, 1)
        self.comboBox_criterio_schedatura = QtGui.QComboBox(DialogInventarioMateriali)
        self.comboBox_criterio_schedatura.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_criterio_schedatura.setFont(font)
        self.comboBox_criterio_schedatura.setMouseTracking(True)
        self.comboBox_criterio_schedatura.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_criterio_schedatura.setEditable(True)
        self.comboBox_criterio_schedatura.setMaxVisibleItems(99999)
        self.comboBox_criterio_schedatura.setMaxCount(2147483647)
        self.comboBox_criterio_schedatura.setFrame(False)
        self.comboBox_criterio_schedatura.setObjectName(_fromUtf8("comboBox_criterio_schedatura"))
        self.comboBox_criterio_schedatura.addItem(_fromUtf8(""))
        self.comboBox_criterio_schedatura.addItem(_fromUtf8(""))
        self.comboBox_criterio_schedatura.addItem(_fromUtf8(""))
        self.comboBox_criterio_schedatura.addItem(_fromUtf8(""))
        self.comboBox_criterio_schedatura.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_criterio_schedatura, 3, 2, 1, 1)
        self.comboBox_definizione = QtGui.QComboBox(DialogInventarioMateriali)
        self.comboBox_definizione.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_definizione.setFont(font)
        self.comboBox_definizione.setMouseTracking(True)
        self.comboBox_definizione.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_definizione.setEditable(True)
        self.comboBox_definizione.setMaxVisibleItems(99999)
        self.comboBox_definizione.setMaxCount(2147483647)
        self.comboBox_definizione.setFrame(False)
        self.comboBox_definizione.setObjectName(_fromUtf8("comboBox_definizione"))
        self.comboBox_definizione.addItem(_fromUtf8(""))
        self.comboBox_definizione.addItem(_fromUtf8(""))
        self.comboBox_definizione.addItem(_fromUtf8(""))
        self.comboBox_definizione.addItem(_fromUtf8(""))
        self.comboBox_definizione.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_definizione, 7, 1, 1, 1)
        self.label_4 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 8, 1, 1, 1)
        self.label_7 = QtGui.QLabel(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget = QtGui.QTabWidget(DialogInventarioMateriali)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.textEdit_descrizione_reperto = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_reperto.setFont(font)
        self.textEdit_descrizione_reperto.setObjectName(_fromUtf8("textEdit_descrizione_reperto"))
        self.horizontalLayout_2.addWidget(self.textEdit_descrizione_reperto)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBox_conservazione = QtGui.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_conservazione.setFont(font)
        self.comboBox_conservazione.setEditable(True)
        self.comboBox_conservazione.setObjectName(_fromUtf8("comboBox_conservazione"))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.comboBox_conservazione.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_conservazione)
        self.label_26 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_2.addWidget(self.label_26)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit_tipo = QtGui.QLineEdit(self.tab)
        self.lineEdit_tipo.setObjectName(_fromUtf8("lineEdit_tipo"))
        self.verticalLayout_4.addWidget(self.lineEdit_tipo)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_4.addWidget(self.label_13)
        self.lineEdit_datazione_rep = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_datazione_rep.setFont(font)
        self.lineEdit_datazione_rep.setText(_fromUtf8(""))
        self.lineEdit_datazione_rep.setObjectName(_fromUtf8("lineEdit_datazione_rep"))
        self.verticalLayout_4.addWidget(self.lineEdit_datazione_rep)
        self.label_41 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_4.addWidget(self.label_41)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.pushButton_insert_row_elementi = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_elementi.setFont(font)
        self.pushButton_insert_row_elementi.setObjectName(_fromUtf8("pushButton_insert_row_elementi"))
        self.gridLayout_9.addWidget(self.pushButton_insert_row_elementi, 0, 1, 1, 1)
        self.pushButton_remove_row_elementi = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_elementi.setFont(font)
        self.pushButton_remove_row_elementi.setObjectName(_fromUtf8("pushButton_remove_row_elementi"))
        self.gridLayout_9.addWidget(self.pushButton_remove_row_elementi, 0, 2, 1, 1)
        self.tableWidget_elementi_reperto = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_elementi_reperto.setMinimumSize(QtCore.QSize(420, 0))
        self.tableWidget_elementi_reperto.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_elementi_reperto.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_elementi_reperto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_elementi_reperto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_elementi_reperto.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_elementi_reperto.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_elementi_reperto.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_elementi_reperto.setRowCount(1)
        self.tableWidget_elementi_reperto.setColumnCount(3)
        self.tableWidget_elementi_reperto.setObjectName(_fromUtf8("tableWidget_elementi_reperto"))
        self.tableWidget_elementi_reperto.setColumnCount(3)
        self.tableWidget_elementi_reperto.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_reperto.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_reperto.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_reperto.setHorizontalHeaderItem(2, item)
        self.gridLayout_9.addWidget(self.tableWidget_elementi_reperto, 1, 0, 1, 3)
        self.gridLayout_16.addLayout(self.gridLayout_9, 0, 0, 3, 1)
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_16.addWidget(self.line, 0, 1, 4, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.lineEdit_diametro_orlo = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_diametro_orlo.setObjectName(_fromUtf8("lineEdit_diametro_orlo"))
        self.gridLayout_11.addWidget(self.lineEdit_diametro_orlo, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_11.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEditFormeMin = QtGui.QLineEdit(self.tab_3)
        self.lineEditFormeMin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditFormeMin.setText(_fromUtf8(""))
        self.lineEditFormeMin.setObjectName(_fromUtf8("lineEditFormeMin"))
        self.gridLayout_11.addWidget(self.lineEditFormeMin, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_11.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEditFormeMax = QtGui.QLineEdit(self.tab_3)
        self.lineEditFormeMax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditFormeMax.setObjectName(_fromUtf8("lineEditFormeMax"))
        self.gridLayout_11.addWidget(self.lineEditFormeMax, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_11.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEditTotFram = QtGui.QLineEdit(self.tab_3)
        self.lineEditTotFram.setEnabled(False)
        self.lineEditTotFram.setObjectName(_fromUtf8("lineEditTotFram"))
        self.gridLayout_11.addWidget(self.lineEditTotFram, 2, 1, 1, 1)
        self.lineEdit_peso = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_peso.setObjectName(_fromUtf8("lineEdit_peso"))
        self.gridLayout_11.addWidget(self.lineEdit_peso, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_11.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_11.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_11.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_11.addWidget(self.label_17, 4, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_11.addWidget(self.label_24, 5, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_11.addWidget(self.label_25, 5, 2, 1, 1)
        self.lineEdit_eve_orlo = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_eve_orlo.setObjectName(_fromUtf8("lineEdit_eve_orlo"))
        self.gridLayout_11.addWidget(self.lineEdit_eve_orlo, 5, 1, 1, 1)
        self.pushButton_tot_fram = QtGui.QPushButton(self.tab_3)
        self.pushButton_tot_fram.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_tot_fram.setObjectName(_fromUtf8("pushButton_tot_fram"))
        self.gridLayout_11.addWidget(self.pushButton_tot_fram, 2, 2, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_11, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 179, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem4, 2, 2, 2, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_10.addWidget(self.label_21, 0, 0, 1, 1)
        self.pushButton_insert_row_misure = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_misure.setFont(font)
        self.pushButton_insert_row_misure.setObjectName(_fromUtf8("pushButton_insert_row_misure"))
        self.gridLayout_10.addWidget(self.pushButton_insert_row_misure, 0, 1, 1, 1)
        self.pushButton_remove_row_misure = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_misure.setFont(font)
        self.pushButton_remove_row_misure.setObjectName(_fromUtf8("pushButton_remove_row_misure"))
        self.gridLayout_10.addWidget(self.pushButton_remove_row_misure, 0, 2, 1, 1)
        self.tableWidget_misurazioni = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_misurazioni.setMinimumSize(QtCore.QSize(420, 0))
        self.tableWidget_misurazioni.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_misurazioni.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_misurazioni.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_misurazioni.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_misurazioni.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_misurazioni.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_misurazioni.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_misurazioni.setRowCount(1)
        self.tableWidget_misurazioni.setColumnCount(3)
        self.tableWidget_misurazioni.setObjectName(_fromUtf8("tableWidget_misurazioni"))
        self.tableWidget_misurazioni.setColumnCount(3)
        self.tableWidget_misurazioni.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(2, item)
        self.gridLayout_10.addWidget(self.tableWidget_misurazioni, 1, 0, 1, 3)
        self.gridLayout_16.addLayout(self.gridLayout_10, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_13.addWidget(self.label_23, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(228, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem5, 0, 1, 1, 2)
        self.pushButton_remove_row_tecnologie = QtGui.QPushButton(self.tab_4)
        self.pushButton_remove_row_tecnologie.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_tecnologie.setFont(font)
        self.pushButton_remove_row_tecnologie.setObjectName(_fromUtf8("pushButton_remove_row_tecnologie"))
        self.gridLayout_13.addWidget(self.pushButton_remove_row_tecnologie, 0, 3, 1, 1)
        self.pushButton_insert_row_tecnologie = QtGui.QPushButton(self.tab_4)
        self.pushButton_insert_row_tecnologie.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_tecnologie.setFont(font)
        self.pushButton_insert_row_tecnologie.setObjectName(_fromUtf8("pushButton_insert_row_tecnologie"))
        self.gridLayout_13.addWidget(self.pushButton_insert_row_tecnologie, 0, 4, 1, 1)
        self.lineEditCorpoCeramico = QtGui.QLineEdit(self.tab_4)
        self.lineEditCorpoCeramico.setObjectName(_fromUtf8("lineEditCorpoCeramico"))
        self.gridLayout_13.addWidget(self.lineEditCorpoCeramico, 1, 0, 1, 2)
        self.tableWidget_tecnologie = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_tecnologie.setMinimumSize(QtCore.QSize(550, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_tecnologie.setFont(font)
        self.tableWidget_tecnologie.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_tecnologie.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_tecnologie.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_tecnologie.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_tecnologie.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_tecnologie.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_tecnologie.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_tecnologie.setRowCount(1)
        self.tableWidget_tecnologie.setColumnCount(5)
        self.tableWidget_tecnologie.setObjectName(_fromUtf8("tableWidget_tecnologie"))
        self.tableWidget_tecnologie.setColumnCount(5)
        self.tableWidget_tecnologie.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tecnologie.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tecnologie.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tecnologie.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tecnologie.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tecnologie.setHorizontalHeaderItem(4, item)
        self.gridLayout_13.addWidget(self.tableWidget_tecnologie, 1, 2, 5, 3)
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_13.addWidget(self.label_12, 2, 0, 1, 2)
        self.lineEditRivestimento = QtGui.QLineEdit(self.tab_4)
        self.lineEditRivestimento.setObjectName(_fromUtf8("lineEditRivestimento"))
        self.gridLayout_13.addWidget(self.lineEditRivestimento, 3, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_13.addWidget(self.label_11, 4, 0, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(20, 136, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem6, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_22 = QtGui.QLabel(self.tab_7)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_12.addWidget(self.label_22, 0, 0, 1, 1)
        self.pushButton_insert_row_rif_biblio = QtGui.QPushButton(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_rif_biblio.setFont(font)
        self.pushButton_insert_row_rif_biblio.setObjectName(_fromUtf8("pushButton_insert_row_rif_biblio"))
        self.gridLayout_12.addWidget(self.pushButton_insert_row_rif_biblio, 0, 1, 1, 1)
        self.pushButton_remove_row_rif_biblio = QtGui.QPushButton(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_rif_biblio.setFont(font)
        self.pushButton_remove_row_rif_biblio.setObjectName(_fromUtf8("pushButton_remove_row_rif_biblio"))
        self.gridLayout_12.addWidget(self.pushButton_remove_row_rif_biblio, 0, 2, 1, 1)
        self.tableWidget_rif_biblio = QtGui.QTableWidget(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_rif_biblio.setFont(font)
        self.tableWidget_rif_biblio.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_rif_biblio.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_rif_biblio.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rif_biblio.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rif_biblio.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_rif_biblio.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_rif_biblio.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_rif_biblio.setRowCount(1)
        self.tableWidget_rif_biblio.setColumnCount(5)
        self.tableWidget_rif_biblio.setObjectName(_fromUtf8("tableWidget_rif_biblio"))
        self.tableWidget_rif_biblio.setColumnCount(5)
        self.tableWidget_rif_biblio.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rif_biblio.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rif_biblio.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rif_biblio.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rif_biblio.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rif_biblio.setHorizontalHeaderItem(4, item)
        self.gridLayout_12.addWidget(self.tableWidget_rif_biblio, 1, 0, 1, 3)
        self.gridLayout_15.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_32 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.gridLayout_24 = QtGui.QGridLayout()
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.gridLayout_26 = QtGui.QGridLayout()
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_26.addWidget(self.label_18, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_26, 0, 0, 1, 2)
        self.line_4 = QtGui.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_25.addWidget(self.line_4, 0, 2, 2, 1)
        self.gridLayout_27 = QtGui.QGridLayout()
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.lineEdit_area = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_area.setFont(font)
        self.lineEdit_area.setText(_fromUtf8(""))
        self.lineEdit_area.setObjectName(_fromUtf8("lineEdit_area"))
        self.gridLayout_27.addWidget(self.lineEdit_area, 0, 0, 1, 2)
        self.label_37 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_27.addWidget(self.label_37, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem8, 1, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_27, 1, 0, 1, 1)
        self.gridLayout_28 = QtGui.QGridLayout()
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.lineEdit_us = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_us.setFont(font)
        self.lineEdit_us.setText(_fromUtf8(""))
        self.lineEdit_us.setObjectName(_fromUtf8("lineEdit_us"))
        self.gridLayout_28.addWidget(self.lineEdit_us, 0, 0, 1, 2)
        self.label_38 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_28.addWidget(self.label_38, 1, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem9, 1, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_28, 1, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_25, 0, 0, 3, 1)
        self.gridLayout_29 = QtGui.QGridLayout()
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_29.addWidget(self.label_19, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(248, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem10, 0, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_29, 0, 1, 1, 1)
        self.gridLayout_30 = QtGui.QGridLayout()
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.label_39 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_30.addWidget(self.label_39, 2, 1, 1, 1)
        self.lineEdit_nr_cassa = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nr_cassa.setFont(font)
        self.lineEdit_nr_cassa.setText(_fromUtf8(""))
        self.lineEdit_nr_cassa.setObjectName(_fromUtf8("lineEdit_nr_cassa"))
        self.gridLayout_30.addWidget(self.lineEdit_nr_cassa, 2, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem11, 2, 3, 1, 1)
        self.comboBox_lavato = QtGui.QComboBox(self.tab_2)
        self.comboBox_lavato.setEditable(True)
        self.comboBox_lavato.setObjectName(_fromUtf8("comboBox_lavato"))
        self.comboBox_lavato.addItem(_fromUtf8(""))
        self.comboBox_lavato.addItem(_fromUtf8(""))
        self.comboBox_lavato.addItem(_fromUtf8(""))
        self.comboBox_lavato.setItemText(2, _fromUtf8(""))
        self.gridLayout_30.addWidget(self.comboBox_lavato, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_30.addWidget(self.label_2, 1, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_30, 1, 1, 1, 1)
        self.gridLayout_31 = QtGui.QGridLayout()
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.label_40 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_31.addWidget(self.label_40, 1, 0, 1, 1)
        self.lineEdit_luogo_conservazione = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_luogo_conservazione.setFont(font)
        self.lineEdit_luogo_conservazione.setText(_fromUtf8(""))
        self.lineEdit_luogo_conservazione.setObjectName(_fromUtf8("lineEdit_luogo_conservazione"))
        self.gridLayout_31.addWidget(self.lineEdit_luogo_conservazione, 1, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_31, 2, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem12, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_6)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.pushButtonQuant = QtGui.QPushButton(self.tab_6)
        self.pushButtonQuant.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonQuant.setObjectName(_fromUtf8("pushButtonQuant"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushButtonQuant)
        self.widget = Mplwidget(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 260))
        self.widget.setStyleSheet(_fromUtf8("background-color: rgb(239, 236, 236);"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.widget)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.formLayout = QtGui.QFormLayout(self.tab_5)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.toolButtonPreviewMedia = QtGui.QToolButton(self.tab_5)
        self.toolButtonPreviewMedia.setEnabled(True)
        self.toolButtonPreviewMedia.setMinimumSize(QtCore.QSize(150, 0))
        self.toolButtonPreviewMedia.setCheckable(True)
        self.toolButtonPreviewMedia.setObjectName(_fromUtf8("toolButtonPreviewMedia"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.toolButtonPreviewMedia)
        self.pushButton_exp_pdf_sheet = QtGui.QPushButton(self.tab_5)
        self.pushButton_exp_pdf_sheet.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_exp_pdf_sheet.setObjectName(_fromUtf8("pushButton_exp_pdf_sheet"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_exp_pdf_sheet)
        spacerItem13 = QtGui.QSpacerItem(590, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtGui.QFormLayout.FieldRole, spacerItem13)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_18.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(DialogInventarioMateriali)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DialogInventarioMateriali)

    def retranslateUi(self, DialogInventarioMateriali):
        DialogInventarioMateriali.setWindowTitle(QtGui.QApplication.translate("DialogInventarioMateriali", "pyArchInit Gestione Scavi - Inventario materiali", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Reload DB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("DialogInventarioMateriali", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito.setItemText(0, QtGui.QApplication.translate("DialogInventarioMateriali", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_num_inv.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Sito", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "N° Inventario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Tipo reperto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(0, QtGui.QApplication.translate("DialogInventarioMateriali", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(1, QtGui.QApplication.translate("DialogInventarioMateriali", "Malacofauna", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(2, QtGui.QApplication.translate("DialogInventarioMateriali", "Reperto cartaceo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(3, QtGui.QApplication.translate("DialogInventarioMateriali", "Reperto ceramico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(4, QtGui.QApplication.translate("DialogInventarioMateriali", "Reperto ligneo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(5, QtGui.QApplication.translate("DialogInventarioMateriali", "Reperto metallico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(6, QtGui.QApplication.translate("DialogInventarioMateriali", "Reperto osseo lavorato", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(7, QtGui.QApplication.translate("DialogInventarioMateriali", "Reperto osteologico animale", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(8, QtGui.QApplication.translate("DialogInventarioMateriali", "Reperto osteologico umano", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_reperto.setItemText(9, QtGui.QApplication.translate("DialogInventarioMateriali", "Reperto vitreo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_criterio_schedatura.setItemText(0, QtGui.QApplication.translate("DialogInventarioMateriali", "Acroma grezza", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_criterio_schedatura.setItemText(1, QtGui.QApplication.translate("DialogInventarioMateriali", "Acroma depurata", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_criterio_schedatura.setItemText(2, QtGui.QApplication.translate("DialogInventarioMateriali", "Maiolica arcaica", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_criterio_schedatura.setItemText(3, QtGui.QApplication.translate("DialogInventarioMateriali", "Vernice nera", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_criterio_schedatura.setItemText(4, QtGui.QApplication.translate("DialogInventarioMateriali", "Terra sigillata", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_definizione.setItemText(0, QtGui.QApplication.translate("DialogInventarioMateriali", "Bicchiere", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_definizione.setItemText(1, QtGui.QApplication.translate("DialogInventarioMateriali", "Boccale", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_definizione.setItemText(2, QtGui.QApplication.translate("DialogInventarioMateriali", "Brocca", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_definizione.setItemText(3, QtGui.QApplication.translate("DialogInventarioMateriali", "Olla", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_definizione.setItemText(4, QtGui.QApplication.translate("DialogInventarioMateriali", "Piatto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Definizione reperto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Classe materiale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(0, QtGui.QApplication.translate("DialogInventarioMateriali", "Insufficiente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(1, QtGui.QApplication.translate("DialogInventarioMateriali", "Scarso", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(2, QtGui.QApplication.translate("DialogInventarioMateriali", "Buono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(3, QtGui.QApplication.translate("DialogInventarioMateriali", "Discreto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(4, QtGui.QApplication.translate("DialogInventarioMateriali", "Ottimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Stato di conservazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Datazione reperto", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogInventarioMateriali", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Elementi reperto", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_elementi.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_elementi.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_reperto.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Elemento rinvenuto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_reperto.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Unita\' di misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_reperto.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Quantita\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Forme minime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Forme massime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Totale frammenti", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Peso", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Diametro orlo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "grammi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "cm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "E.v.e. orlo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tot_fram.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "calc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Misurazioni", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_misure.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_misure.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Tipo di misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Unita\' di misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Quantita\'", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("DialogInventarioMateriali", "Dati quantitativi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Tecnologie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_tecnologie.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_tecnologie.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tecnologie.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Tipo tecnologia", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tecnologie.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Posizione", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tecnologie.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Tipo quantità", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tecnologie.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Unità di misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tecnologie.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Qtà", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Corpo ceramico", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Rivestimento", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("DialogInventarioMateriali", "Tecnologie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Rif. Bibliografici", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_rif_biblio.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_rif_biblio.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "rimuovi riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rif_biblio.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Autore", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rif_biblio.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Anno", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rif_biblio.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Titolo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rif_biblio.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Pag.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rif_biblio.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Fig.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("DialogInventarioMateriali", "Rif Biblio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Dati stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Dati magazzino", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Nr. Cassa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_lavato.setItemText(0, QtGui.QApplication.translate("DialogInventarioMateriali", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_lavato.setItemText(1, QtGui.QApplication.translate("DialogInventarioMateriali", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Lavato", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Luogo di conservazione", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogInventarioMateriali", "Rif. stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonQuant.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Impostazione quantificazione", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("DialogInventarioMateriali", "Quantificazioni", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreviewMedia.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Media Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exp_pdf_sheet.setText(QtGui.QApplication.translate("DialogInventarioMateriali", "Exp schede Pdf ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("DialogInventarioMateriali", "Tools", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import Mplwidget
