# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_Ipogei_ui.ui'
#
# Created: Fri Oct 26 11:29:48 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogIpogei(object):
    def setupUi(self, DialogIpogei):
        DialogIpogei.setObjectName("DialogIpogei")
        DialogIpogei.resize(540, 766)
        DialogIpogei.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/iconStrutt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogIpogei.setWindowIcon(icon)
        self.gridLayout_8 = QtGui.QGridLayout(DialogIpogei)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(DialogIpogei)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_first_rec = QtGui.QPushButton(DialogIpogei)
        self.pushButton_first_rec.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/5_leftArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName("pushButton_first_rec")
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 0, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogIpogei)
        self.pushButton_prev_rec.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/4_leftArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon2)
        self.pushButton_prev_rec.setObjectName("pushButton_prev_rec")
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 1, 1, 2)
        self.pushButton_next_rec = QtGui.QPushButton(DialogIpogei)
        self.pushButton_next_rec.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/6_rightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon3)
        self.pushButton_next_rec.setObjectName("pushButton_next_rec")
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(DialogIpogei)
        self.pushButton_last_rec.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/7_rightArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon4)
        self.pushButton_last_rec.setObjectName("pushButton_last_rec")
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/newrec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon5)
        self.pushButton_new_rec.setObjectName("pushButton_new_rec")
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/b_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon6)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon7)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(70, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/new_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName("pushButton_new_search")
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon9)
        self.pushButton_search_go.setObjectName("pushButton_search_go")
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon10)
        self.pushButton_sort.setObjectName("pushButton_sort")
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/view_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon11)
        self.pushButton_view_all.setObjectName("pushButton_view_all")
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(DialogIpogei)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_42 = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_43 = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogIpogei)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName("label_status")
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText("")
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName("label_sort")
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName("label_rec_corrente")
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(DialogIpogei)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName("label_rec_tot")
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_8 = QtGui.QFrame(DialogIpogei)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.comboBox_sito_ipogeo = QtGui.QComboBox(DialogIpogei)
        self.comboBox_sito_ipogeo.setEnabled(False)
        self.comboBox_sito_ipogeo.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito_ipogeo.setFont(font)
        self.comboBox_sito_ipogeo.setMouseTracking(True)
        self.comboBox_sito_ipogeo.setEditable(True)
        self.comboBox_sito_ipogeo.setMaxVisibleItems(99999)
        self.comboBox_sito_ipogeo.setMaxCount(2147483647)
        self.comboBox_sito_ipogeo.setObjectName("comboBox_sito_ipogeo")
        self.gridLayout_18.addWidget(self.comboBox_sito_ipogeo, 0, 0, 1, 1)
        self.numero_ipogeo = QtGui.QLineEdit(DialogIpogei)
        self.numero_ipogeo.setEnabled(False)
        self.numero_ipogeo.setMinimumSize(QtCore.QSize(61, 21))
        self.numero_ipogeo.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.numero_ipogeo.setFont(font)
        self.numero_ipogeo.setObjectName("numero_ipogeo")
        self.gridLayout_18.addWidget(self.numero_ipogeo, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(DialogIpogei)
        self.label_2.setObjectName("label_2")
        self.gridLayout_18.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(DialogIpogei)
        self.label_3.setObjectName("label_3")
        self.gridLayout_18.addWidget(self.label_3, 1, 2, 1, 1)
        self.comboBox_sigla_ipogeo = QtGui.QComboBox(DialogIpogei)
        self.comboBox_sigla_ipogeo.setEnabled(False)
        self.comboBox_sigla_ipogeo.setMinimumSize(QtCore.QSize(90, 0))
        self.comboBox_sigla_ipogeo.setMaximumSize(QtCore.QSize(90, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sigla_ipogeo.setFont(font)
        self.comboBox_sigla_ipogeo.setEditable(True)
        self.comboBox_sigla_ipogeo.setObjectName("comboBox_sigla_ipogeo")
        self.comboBox_sigla_ipogeo.addItem("")
        self.comboBox_sigla_ipogeo.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_sigla_ipogeo, 0, 1, 1, 1)
        self.label = QtGui.QLabel(DialogIpogei)
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_18)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_categoria_ipogeo = QtGui.QComboBox(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_categoria_ipogeo.setFont(font)
        self.comboBox_categoria_ipogeo.setEditable(True)
        self.comboBox_categoria_ipogeo.setObjectName("comboBox_categoria_ipogeo")
        self.gridLayout_6.addWidget(self.comboBox_categoria_ipogeo, 0, 0, 1, 1)
        self.comboBox_tipologia_ipogeo = QtGui.QComboBox(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_tipologia_ipogeo.setFont(font)
        self.comboBox_tipologia_ipogeo.setEditable(True)
        self.comboBox_tipologia_ipogeo.setObjectName("comboBox_tipologia_ipogeo")
        self.gridLayout_6.addWidget(self.comboBox_tipologia_ipogeo, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(DialogIpogei)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(DialogIpogei)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 1, 1, 1)
        self.comboBox_definizione_ipogeo = QtGui.QComboBox(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_definizione_ipogeo.setFont(font)
        self.comboBox_definizione_ipogeo.setEditable(True)
        self.comboBox_definizione_ipogeo.setObjectName("comboBox_definizione_ipogeo")
        self.gridLayout_6.addWidget(self.comboBox_definizione_ipogeo, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(DialogIpogei)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(DialogIpogei)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_percentuale_umidita_ipogeo = QtGui.QComboBox(self.tab)
        self.comboBox_percentuale_umidita_ipogeo.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_percentuale_umidita_ipogeo.setEditable(True)
        self.comboBox_percentuale_umidita_ipogeo.setObjectName("comboBox_percentuale_umidita_ipogeo")
        self.gridLayout_7.addWidget(self.comboBox_percentuale_umidita_ipogeo, 0, 0, 1, 1)
        self.comboBox_grado_conservazione_ipogeo = QtGui.QComboBox(self.tab)
        self.comboBox_grado_conservazione_ipogeo.setEditable(True)
        self.comboBox_grado_conservazione_ipogeo.setObjectName("comboBox_grado_conservazione_ipogeo")
        self.gridLayout_7.addWidget(self.comboBox_grado_conservazione_ipogeo, 0, 1, 1, 1)
        self.comboBox_grado_staticita_ipogeo = QtGui.QComboBox(self.tab)
        self.comboBox_grado_staticita_ipogeo.setEditable(True)
        self.comboBox_grado_staticita_ipogeo.setObjectName("comboBox_grado_staticita_ipogeo")
        self.gridLayout_7.addWidget(self.comboBox_grado_staticita_ipogeo, 0, 2, 1, 2)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 1, 1, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.descrizione_ipogeo = QtGui.QTextEdit(self.tab)
        self.descrizione_ipogeo.setMinimumSize(QtCore.QSize(400, 150))
        self.descrizione_ipogeo.setMaximumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.descrizione_ipogeo.setFont(font)
        self.descrizione_ipogeo.setObjectName("descrizione_ipogeo")
        self.verticalLayout_5.addWidget(self.descrizione_ipogeo)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.textEdit_interpretazione_ipogeo = QtGui.QTextEdit(self.tab)
        self.textEdit_interpretazione_ipogeo.setMinimumSize(QtCore.QSize(0, 150))
        self.textEdit_interpretazione_ipogeo.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione_ipogeo.setFont(font)
        self.textEdit_interpretazione_ipogeo.setObjectName("textEdit_interpretazione_ipogeo")
        self.verticalLayout_5.addWidget(self.textEdit_interpretazione_ipogeo)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 2, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 3, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 2, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_15.addWidget(self.label_12, 0, 0, 1, 4)
        self.label_37 = QtGui.QLabel(self.tab_2)
        self.label_37.setMinimumSize(QtCore.QSize(0, 15))
        self.label_37.setObjectName("label_37")
        self.gridLayout_15.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 15))
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 1, 3, 1, 1)
        self.comboBox_per_iniz_ipogeo = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_iniz_ipogeo.setObjectName("comboBox_per_iniz_ipogeo")
        self.comboBox_per_iniz_ipogeo.addItem("")
        self.comboBox_per_iniz_ipogeo.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_per_iniz_ipogeo, 3, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_15.addWidget(self.label_32, 4, 4, 1, 1)
        self.comboBox_fas_iniz_ipogeo = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_iniz_ipogeo.setObjectName("comboBox_fas_iniz_ipogeo")
        self.gridLayout_15.addWidget(self.comboBox_fas_iniz_ipogeo, 3, 1, 1, 1)
        self.comboBox_per_fin_ipogeo = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_fin_ipogeo.setObjectName("comboBox_per_fin_ipogeo")
        self.gridLayout_15.addWidget(self.comboBox_per_fin_ipogeo, 3, 3, 1, 1)
        self.comboBox_fas_fin_ipogeo = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_fin_ipogeo.setObjectName("comboBox_fas_fin_ipogeo")
        self.gridLayout_15.addWidget(self.comboBox_fas_fin_ipogeo, 3, 4, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_15)
        self.lineEdit_datazione_estesa_ipogeo = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_datazione_estesa_ipogeo.setObjectName("lineEdit_datazione_estesa_ipogeo")
        self.verticalLayout_8.addWidget(self.lineEdit_datazione_estesa_ipogeo)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_9.addLayout(self.gridLayout_16)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_10.addWidget(self.line_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.pushButton_insert_row_rapporti = QtGui.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_rapporti.setFont(font)
        self.pushButton_insert_row_rapporti.setObjectName("pushButton_insert_row_rapporti")
        self.horizontalLayout_4.addWidget(self.pushButton_insert_row_rapporti)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_14.addLayout(self.verticalLayout_11)
        self.tableWidget_rapporti_ipogeo = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_rapporti_ipogeo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_rapporti_ipogeo.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_rapporti_ipogeo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti_ipogeo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti_ipogeo.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_rapporti_ipogeo.setRowCount(1)
        self.tableWidget_rapporti_ipogeo.setColumnCount(4)
        self.tableWidget_rapporti_ipogeo.setObjectName("tableWidget_rapporti_ipogeo")
        self.tableWidget_rapporti_ipogeo.setColumnCount(4)
        self.tableWidget_rapporti_ipogeo.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti_ipogeo.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti_ipogeo.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti_ipogeo.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti_ipogeo.setHorizontalHeaderItem(3, item)
        self.verticalLayout_14.addWidget(self.tableWidget_rapporti_ipogeo)
        self.gridLayout_17.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_insert_row_elementi = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_elementi.setGeometry(QtCore.QRect(150, 150, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_elementi.setFont(font)
        self.pushButton_insert_row_elementi.setObjectName("pushButton_insert_row_elementi")
        self.label_11_ipogeo = QtGui.QLabel(self.tab_3)
        self.label_11_ipogeo.setGeometry(QtCore.QRect(27, 157, 121, 17))
        self.label_11_ipogeo.setObjectName("label_11_ipogeo")
        self.tableWidget_elementi_strutturali_ipogeo = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_elementi_strutturali_ipogeo.setGeometry(QtCore.QRect(27, 182, 581, 80))
        self.tableWidget_elementi_strutturali_ipogeo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_elementi_strutturali_ipogeo.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_elementi_strutturali_ipogeo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_elementi_strutturali_ipogeo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_elementi_strutturali_ipogeo.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_elementi_strutturali_ipogeo.setRowCount(1)
        self.tableWidget_elementi_strutturali_ipogeo.setColumnCount(2)
        self.tableWidget_elementi_strutturali_ipogeo.setObjectName("tableWidget_elementi_strutturali_ipogeo")
        self.tableWidget_elementi_strutturali_ipogeo.setColumnCount(2)
        self.tableWidget_elementi_strutturali_ipogeo.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_strutturali_ipogeo.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_elementi_strutturali_ipogeo.setHorizontalHeaderItem(1, item)
        self.label_15_ipogeo = QtGui.QLabel(self.tab_3)
        self.label_15_ipogeo.setGeometry(QtCore.QRect(27, 303, 76, 17))
        self.label_15_ipogeo.setObjectName("label_15_ipogeo")
        self.tableWidget_misurazioni_ipogeo = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_misurazioni_ipogeo.setGeometry(QtCore.QRect(27, 328, 581, 80))
        self.tableWidget_misurazioni_ipogeo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_misurazioni_ipogeo.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_misurazioni_ipogeo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_misurazioni_ipogeo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_misurazioni_ipogeo.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_misurazioni_ipogeo.setRowCount(1)
        self.tableWidget_misurazioni_ipogeo.setColumnCount(3)
        self.tableWidget_misurazioni_ipogeo.setObjectName("tableWidget_misurazioni_ipogeo")
        self.tableWidget_misurazioni_ipogeo.setColumnCount(3)
        self.tableWidget_misurazioni_ipogeo.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni_ipogeo.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni_ipogeo.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni_ipogeo.setHorizontalHeaderItem(2, item)
        self.pushButton_insert_row_misurazioni = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_misurazioni.setGeometry(QtCore.QRect(100, 300, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_misurazioni.setFont(font)
        self.pushButton_insert_row_misurazioni.setObjectName("pushButton_insert_row_misurazioni")
        self.tableWidget_materiali_impiegati_ipogeo = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_materiali_impiegati_ipogeo.setGeometry(QtCore.QRect(30, 30, 581, 101))
        self.tableWidget_materiali_impiegati_ipogeo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_materiali_impiegati_ipogeo.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_materiali_impiegati_ipogeo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_materiali_impiegati_ipogeo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_materiali_impiegati_ipogeo.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_materiali_impiegati_ipogeo.setRowCount(1)
        self.tableWidget_materiali_impiegati_ipogeo.setColumnCount(1)
        self.tableWidget_materiali_impiegati_ipogeo.setObjectName("tableWidget_materiali_impiegati_ipogeo")
        self.tableWidget_materiali_impiegati_ipogeo.setColumnCount(1)
        self.tableWidget_materiali_impiegati_ipogeo.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_materiali_impiegati_ipogeo.setHorizontalHeaderItem(0, item)
        self.label_8_ipogeo = QtGui.QLabel(self.tab_3)
        self.label_8_ipogeo.setGeometry(QtCore.QRect(30, 10, 117, 17))
        self.label_8_ipogeo.setObjectName("label_8_ipogeo")
        self.pushButton_insert_row_materiali = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_materiali.setGeometry(QtCore.QRect(150, 0, 102, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_materiali.setFont(font)
        self.pushButton_insert_row_materiali.setObjectName("pushButton_insert_row_materiali")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_view_geometry = QtGui.QPushButton(self.tab_4)
        self.pushButton_view_geometry.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton_view_geometry.setObjectName("pushButton_view_geometry")
        self.toolButton_view_search = QtGui.QToolButton(self.tab_4)
        self.toolButton_view_search.setGeometry(QtCore.QRect(14, 48, 71, 21))
        self.toolButton_view_search.setObjectName("toolButton_view_search")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_8.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(DialogIpogei)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogIpogei)

    def retranslateUi(self, DialogIpogei):
        DialogIpogei.setWindowTitle(QtGui.QApplication.translate("DialogIpogei", "pyArchInit Gestione Ipogei-Scheda Ipogeo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DialogIpogei", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("DialogIpogei", "Reload DB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("DialogIpogei", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("DialogIpogei", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("DialogIpogei", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("DialogIpogei", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("DialogIpogei", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("DialogIpogei", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("DialogIpogei", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("DialogIpogei", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("DialogIpogei", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("DialogIpogei", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("DialogIpogei", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("DialogIpogei", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("DialogIpogei", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DialogIpogei", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("DialogIpogei", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("DialogIpogei", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DialogIpogei", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("DialogIpogei", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogIpogei", "Sigla ipogeo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogIpogei", "N° ipogeo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigla_ipogeo.setItemText(0, QtGui.QApplication.translate("DialogIpogei", "Aggiungi un valore...", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigla_ipogeo.setItemText(1, QtGui.QApplication.translate("DialogIpogei", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogIpogei", "Sito ipogeo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogIpogei", "Categoria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogIpogei", "Tipologia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogIpogei", "Definizione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogIpogei", "Percentuale umidità", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogIpogei", "Grado di conservazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogIpogei", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.descrizione_ipogeo.setHtml(QtGui.QApplication.translate("DialogIpogei", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\"><br /></span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogIpogei", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogIpogei", "Interpretazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogIpogei", "Grado di staticità", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogIpogei", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("DialogIpogei", "Periodizzazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("DialogIpogei", "Iniziale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogIpogei", "Finale ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_per_iniz_ipogeo.setItemText(0, QtGui.QApplication.translate("DialogIpogei", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_per_iniz_ipogeo.setItemText(1, QtGui.QApplication.translate("DialogIpogei", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("DialogIpogei", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogIpogei", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogIpogei", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("DialogIpogei", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("DialogIpogei", "Datazione estesa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("DialogIpogei", "Rapporti struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_rapporti.setText(QtGui.QApplication.translate("DialogIpogei", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti_ipogeo.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogIpogei", "Tipo di rapporto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti_ipogeo.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogIpogei", "Sito", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti_ipogeo.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogIpogei", "Sigla", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti_ipogeo.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DialogIpogei", "Numero", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogIpogei", "Periodizzazione - Rapporti", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_elementi.setText(QtGui.QApplication.translate("DialogIpogei", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11_ipogeo.setText(QtGui.QApplication.translate("DialogIpogei", "Elementi strutturali", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_strutturali_ipogeo.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogIpogei", "Tipologia elemnto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_elementi_strutturali_ipogeo.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogIpogei", "Quantità", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15_ipogeo.setText(QtGui.QApplication.translate("DialogIpogei", "Misurazione", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni_ipogeo.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogIpogei", "Tipo misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni_ipogeo.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogIpogei", "Unita\' di misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni_ipogeo.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogIpogei", "Valore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_misurazioni.setText(QtGui.QApplication.translate("DialogIpogei", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_materiali_impiegati_ipogeo.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogIpogei", "Materiali", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8_ipogeo.setText(QtGui.QApplication.translate("DialogIpogei", "Materiali impiegati", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_materiali.setText(QtGui.QApplication.translate("DialogIpogei", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("DialogIpogei", "Elementi costruttivi", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_geometry.setText(QtGui.QApplication.translate("DialogIpogei", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_view_search.setText(QtGui.QApplication.translate("DialogIpogei", "Visualizza", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("DialogIpogei", "Tools", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
