# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_image_viewer_dialog.ui'
#
# Created: Mon Aug 29 17:06:55 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogImageViewer(object):
    def setupUi(self, DialogImageViewer):
        DialogImageViewer.setObjectName("DialogImageViewer")
        DialogImageViewer.resize(986, 664)
        self.gridLayout_2 = QtGui.QGridLayout(DialogImageViewer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtGui.QSplitter(DialogImageViewer)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.iconListWidget = QtGui.QListWidget(self.layoutWidget)
        self.iconListWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.iconListWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.iconListWidget.setLineWidth(2)
        self.iconListWidget.setMidLineWidth(2)
        self.iconListWidget.setProperty("showDropIndicator", False)
        self.iconListWidget.setIconSize(QtCore.QSize(150, 150))
        self.iconListWidget.setMovement(QtGui.QListView.Snap)
        self.iconListWidget.setResizeMode(QtGui.QListView.Adjust)
        self.iconListWidget.setLayoutMode(QtGui.QListView.Batched)
        self.iconListWidget.setGridSize(QtCore.QSize(160, 160))
        self.iconListWidget.setViewMode(QtGui.QListView.IconMode)
        self.iconListWidget.setUniformItemSizes(True)
        self.iconListWidget.setBatchSize(1000)
        self.iconListWidget.setObjectName("iconListWidget")
        self.gridLayout.addWidget(self.iconListWidget, 0, 0, 1, 3)
        self.pushButton_openMedia = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_openMedia.setObjectName("pushButton_openMedia")
        self.gridLayout.addWidget(self.pushButton_openMedia, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.pushButton_chose_dir = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_chose_dir.setObjectName("pushButton_chose_dir")
        self.gridLayout.addWidget(self.pushButton_chose_dir, 2, 1, 1, 2)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_addRow = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_addRow.setObjectName("pushButton_addRow")
        self.horizontalLayout.addWidget(self.pushButton_addRow)
        self.pushButton_removeRow = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_removeRow.setObjectName("pushButton_removeRow")
        self.horizontalLayout.addWidget(self.pushButton_removeRow)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidgetTags = QtGui.QTableWidget(self.layoutWidget1)
        self.tableWidgetTags.setObjectName("tableWidgetTags")
        self.tableWidgetTags.setColumnCount(3)
        self.tableWidgetTags.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTags.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTags.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTags.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTags.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidgetTags)
        self.pushButton_assignTags = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_assignTags.setObjectName("pushButton_assignTags")
        self.verticalLayout_2.addWidget(self.pushButton_assignTags)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(DialogImageViewer)
        QtCore.QMetaObject.connectSlotsByName(DialogImageViewer)

    def retranslateUi(self, DialogImageViewer):
        DialogImageViewer.setWindowTitle(QtGui.QApplication.translate("DialogImageViewer", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_openMedia.setText(QtGui.QApplication.translate("DialogImageViewer", "Apri Immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_chose_dir.setText(QtGui.QApplication.translate("DialogImageViewer", "Carica le immagini nel DB", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogImageViewer", "Tags manager", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_addRow.setText(QtGui.QApplication.translate("DialogImageViewer", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_removeRow.setText(QtGui.QApplication.translate("DialogImageViewer", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetTags.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogImageViewer", "Sito", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetTags.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogImageViewer", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetTags.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogImageViewer", "US", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_assignTags.setText(QtGui.QApplication.translate("DialogImageViewer", "Assegna i tags", None, QtGui.QApplication.UnicodeUTF8))

